/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftSqlFunctionHandle", builder=ThriftSqlFunctionHandle.Builder.class)
public final class ThriftSqlFunctionHandle implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftSqlFunctionHandle(
        @com.facebook.swift.codec.ThriftField(value=1, name="functionId", requiredness=Requiredness.NONE) final com.facebook.presto.common.experimental.auto_gen.ThriftSqlFunctionId functionId,
        @com.facebook.swift.codec.ThriftField(value=2, name="version", requiredness=Requiredness.NONE) final String version
    ) {
        this.functionId = functionId;
        this.version = version;
    }
    
    @ThriftConstructor
    protected ThriftSqlFunctionHandle() {
      this.functionId = null;
      this.version = null;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftSqlFunctionHandle other) {
      return new Builder(other);
    }

    public static class Builder {
        private com.facebook.presto.common.experimental.auto_gen.ThriftSqlFunctionId functionId = null;
        private String version = null;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="functionId", requiredness=Requiredness.NONE)    public Builder setFunctionId(com.facebook.presto.common.experimental.auto_gen.ThriftSqlFunctionId functionId) {
            this.functionId = functionId;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftSqlFunctionId getFunctionId() { return functionId; }
    
            @com.facebook.swift.codec.ThriftField(value=2, name="version", requiredness=Requiredness.NONE)    public Builder setVersion(String version) {
            this.version = version;
            return this;
        }
    
        public String getVersion() { return version; }
    
        public Builder() { }
        public Builder(ThriftSqlFunctionHandle other) {
            this.functionId = other.functionId;
            this.version = other.version;
        }
    
        @ThriftConstructor
        public ThriftSqlFunctionHandle build() {
            ThriftSqlFunctionHandle result = new ThriftSqlFunctionHandle (
                this.functionId,
                this.version
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftSqlFunctionHandle");
    private final com.facebook.presto.common.experimental.auto_gen.ThriftSqlFunctionId functionId;
    public static final int _FUNCTIONID = 1;
    private static final TField FUNCTION_ID_FIELD_DESC = new TField("functionId", TType.STRUCT, (short)1);
        private final String version;
    public static final int _VERSION = 2;
    private static final TField VERSION_FIELD_DESC = new TField("version", TType.STRING, (short)2);
    static {
      NAMES_TO_IDS.put("functionId", 1);
      THRIFT_NAMES_TO_IDS.put("functionId", 1);
      FIELD_METADATA.put(1, FUNCTION_ID_FIELD_DESC);
      NAMES_TO_IDS.put("version", 2);
      THRIFT_NAMES_TO_IDS.put("version", 2);
      FIELD_METADATA.put(2, VERSION_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="functionId", requiredness=Requiredness.NONE)
    public com.facebook.presto.common.experimental.auto_gen.ThriftSqlFunctionId getFunctionId() { return functionId; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=2, name="version", requiredness=Requiredness.NONE)
    public String getVersion() { return version; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("functionId", functionId);
        helper.add("version", version);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftSqlFunctionHandle other = (ThriftSqlFunctionHandle)o;
    
        return
            Objects.equals(functionId, other.functionId) &&
            Objects.equals(version, other.version) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            functionId,
            version
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftSqlFunctionHandle> asReader() {
      return ThriftSqlFunctionHandle::read0;
    }
    
    public static ThriftSqlFunctionHandle read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftSqlFunctionHandle.NAMES_TO_IDS, ThriftSqlFunctionHandle.THRIFT_NAMES_TO_IDS, ThriftSqlFunctionHandle.FIELD_METADATA);
      ThriftSqlFunctionHandle.Builder builder = new ThriftSqlFunctionHandle.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _FUNCTIONID:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftSqlFunctionId functionId = com.facebook.presto.common.experimental.auto_gen.ThriftSqlFunctionId.read0(oprot);
            builder.setFunctionId(functionId);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _VERSION:
          if (__field.type == TType.STRING) {
            String version = oprot.readString();
            builder.setVersion(version);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (functionId != null) {
        oprot.writeFieldBegin(FUNCTION_ID_FIELD_DESC);
        this.functionId.write0(oprot);
        oprot.writeFieldEnd();
      }
      if (version != null) {
        oprot.writeFieldBegin(VERSION_FIELD_DESC);
        oprot.writeString(this.version);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftSqlFunctionHandleLazy {
        private static final ThriftSqlFunctionHandle _DEFAULT = new ThriftSqlFunctionHandle.Builder().build();
    }
    
    public static ThriftSqlFunctionHandle defaultInstance() {
        return  _ThriftSqlFunctionHandleLazy._DEFAULT;
    }
}
