/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import org.apache.fbthrift.TException;
import org.apache.fbthrift.protocol.TProtocol;

@SwiftGenerated
public enum ThriftFunctionHandleType implements com.facebook.thrift.enums.BaseEnum, com.facebook.thrift.payload.ThriftSerializable {
    BUILTIN_HANDLE(1),
    HIVE_HANDLE(2),
    NATIVE_HANDLE(3),
    REST_HANDLE(4),
    SESSION_HANDLE(5),
    SQL_HANDLE(6);

    private final int value;

    ThriftFunctionHandleType(int value) {
        this.value = value;
    }

    @ThriftEnumValue
    public int getValue() {
        return value;
    }

    public static ThriftFunctionHandleType fromInteger(int n) {
        switch (n) {
        case 1:
            return BUILTIN_HANDLE;
        case 2:
            return HIVE_HANDLE;
        case 3:
            return NATIVE_HANDLE;
        case 4:
            return REST_HANDLE;
        case 5:
            return SESSION_HANDLE;
        case 6:
            return SQL_HANDLE;
        default:
            return null;
        }
    }

    public static com.facebook.thrift.payload.Reader<ThriftFunctionHandleType> asReader() {
        return ThriftFunctionHandleType::read0;
    }

    public static ThriftFunctionHandleType read0(TProtocol iprot) throws TException {
        return ThriftFunctionHandleType.fromInteger(iprot.readI32());
    }

    public void write0(TProtocol oprot) throws TException {
        oprot.writeI32(getValue());
    }


}
