/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftLongSubscriptElement", builder=ThriftLongSubscriptElement.Builder.class)
public final class ThriftLongSubscriptElement implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftLongSubscriptElement(
        @com.facebook.swift.codec.ThriftField(value=1, name="index", requiredness=Requiredness.NONE) final long index
    ) {
        this.index = index;
    }
    
    @ThriftConstructor
    protected ThriftLongSubscriptElement() {
      this.index = 0L;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftLongSubscriptElement other) {
      return new Builder(other);
    }

    public static class Builder {
        private long index = 0L;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="index", requiredness=Requiredness.NONE)    public Builder setIndex(long index) {
            this.index = index;
            return this;
        }
    
        public long getIndex() { return index; }
    
        public Builder() { }
        public Builder(ThriftLongSubscriptElement other) {
            this.index = other.index;
        }
    
        @ThriftConstructor
        public ThriftLongSubscriptElement build() {
            ThriftLongSubscriptElement result = new ThriftLongSubscriptElement (
                this.index
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftLongSubscriptElement");
    private final long index;
    public static final int _INDEX = 1;
    private static final TField INDEX_FIELD_DESC = new TField("index", TType.I64, (short)1);
    static {
      NAMES_TO_IDS.put("index", 1);
      THRIFT_NAMES_TO_IDS.put("index", 1);
      FIELD_METADATA.put(1, INDEX_FIELD_DESC);
    }
    
    
    @com.facebook.swift.codec.ThriftField(value=1, name="index", requiredness=Requiredness.NONE)
    public long getIndex() { return index; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("index", index);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftLongSubscriptElement other = (ThriftLongSubscriptElement)o;
    
        return
            Objects.equals(index, other.index) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            index
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftLongSubscriptElement> asReader() {
      return ThriftLongSubscriptElement::read0;
    }
    
    public static ThriftLongSubscriptElement read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftLongSubscriptElement.NAMES_TO_IDS, ThriftLongSubscriptElement.THRIFT_NAMES_TO_IDS, ThriftLongSubscriptElement.FIELD_METADATA);
      ThriftLongSubscriptElement.Builder builder = new ThriftLongSubscriptElement.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _INDEX:
          if (__field.type == TType.I64) {
            long index = oprot.readI64();
            builder.setIndex(index);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(INDEX_FIELD_DESC);
      oprot.writeI64(this.index);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftLongSubscriptElementLazy {
        private static final ThriftLongSubscriptElement _DEFAULT = new ThriftLongSubscriptElement.Builder().build();
    }
    
    public static ThriftLongSubscriptElement defaultInstance() {
        return  _ThriftLongSubscriptElementLazy._DEFAULT;
    }
}
