/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftFunctionVersion", builder=ThriftFunctionVersion.Builder.class)
public final class ThriftFunctionVersion implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftFunctionVersion(
        @com.facebook.swift.codec.ThriftField(value=1, name="version", requiredness=Requiredness.OPTIONAL) final String version
    ) {
        this.version = version;
    }
    
    @ThriftConstructor
    protected ThriftFunctionVersion() {
      this.version = null;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftFunctionVersion other) {
      return new Builder(other);
    }

    public static class Builder {
        private String version = null;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="version", requiredness=Requiredness.OPTIONAL)    public Builder setVersion(String version) {
            this.version = version;
            return this;
        }
    
        public String getVersion() { return version; }
    
        public Builder() { }
        public Builder(ThriftFunctionVersion other) {
            this.version = other.version;
        }
    
        @ThriftConstructor
        public ThriftFunctionVersion build() {
            ThriftFunctionVersion result = new ThriftFunctionVersion (
                this.version
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftFunctionVersion");
    private final String version;
    public static final int _VERSION = 1;
    private static final TField VERSION_FIELD_DESC = new TField("version", TType.STRING, (short)1);
    static {
      NAMES_TO_IDS.put("version", 1);
      THRIFT_NAMES_TO_IDS.put("version", 1);
      FIELD_METADATA.put(1, VERSION_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="version", requiredness=Requiredness.OPTIONAL)
    public String getVersion() { return version; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("version", version);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftFunctionVersion other = (ThriftFunctionVersion)o;
    
        return
            Objects.equals(version, other.version) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            version
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftFunctionVersion> asReader() {
      return ThriftFunctionVersion::read0;
    }
    
    public static ThriftFunctionVersion read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftFunctionVersion.NAMES_TO_IDS, ThriftFunctionVersion.THRIFT_NAMES_TO_IDS, ThriftFunctionVersion.FIELD_METADATA);
      ThriftFunctionVersion.Builder builder = new ThriftFunctionVersion.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _VERSION:
          if (__field.type == TType.STRING) {
            String  version = oprot.readString();
            builder.setVersion(version);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (version != null) {
        oprot.writeFieldBegin(VERSION_FIELD_DESC);
        oprot.writeString(this.version);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftFunctionVersionLazy {
        private static final ThriftFunctionVersion _DEFAULT = new ThriftFunctionVersion.Builder().build();
    }
    
    public static ThriftFunctionVersion defaultInstance() {
        return  _ThriftFunctionVersionLazy._DEFAULT;
    }
}
