/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftHiveType", builder=ThriftHiveType.Builder.class)
public final class ThriftHiveType implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftHiveType(
        @com.facebook.swift.codec.ThriftField(value=1, name="typeInfo", requiredness=Requiredness.NONE) final com.facebook.presto.common.experimental.auto_gen.ThriftTypeInfo typeInfo
    ) {
        this.typeInfo = typeInfo;
    }
    
    @ThriftConstructor
    protected ThriftHiveType() {
      this.typeInfo = null;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftHiveType other) {
      return new Builder(other);
    }

    public static class Builder {
        private com.facebook.presto.common.experimental.auto_gen.ThriftTypeInfo typeInfo = null;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="typeInfo", requiredness=Requiredness.NONE)    public Builder setTypeInfo(com.facebook.presto.common.experimental.auto_gen.ThriftTypeInfo typeInfo) {
            this.typeInfo = typeInfo;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftTypeInfo getTypeInfo() { return typeInfo; }
    
        public Builder() { }
        public Builder(ThriftHiveType other) {
            this.typeInfo = other.typeInfo;
        }
    
        @ThriftConstructor
        public ThriftHiveType build() {
            ThriftHiveType result = new ThriftHiveType (
                this.typeInfo
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftHiveType");
    private final com.facebook.presto.common.experimental.auto_gen.ThriftTypeInfo typeInfo;
    public static final int _TYPEINFO = 1;
    private static final TField TYPE_INFO_FIELD_DESC = new TField("typeInfo", TType.STRUCT, (short)1);
    static {
      NAMES_TO_IDS.put("typeInfo", 1);
      THRIFT_NAMES_TO_IDS.put("typeInfo", 1);
      FIELD_METADATA.put(1, TYPE_INFO_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="typeInfo", requiredness=Requiredness.NONE)
    public com.facebook.presto.common.experimental.auto_gen.ThriftTypeInfo getTypeInfo() { return typeInfo; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("typeInfo", typeInfo);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftHiveType other = (ThriftHiveType)o;
    
        return
            Objects.equals(typeInfo, other.typeInfo) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            typeInfo
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftHiveType> asReader() {
      return ThriftHiveType::read0;
    }
    
    public static ThriftHiveType read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftHiveType.NAMES_TO_IDS, ThriftHiveType.THRIFT_NAMES_TO_IDS, ThriftHiveType.FIELD_METADATA);
      ThriftHiveType.Builder builder = new ThriftHiveType.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _TYPEINFO:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftTypeInfo typeInfo = com.facebook.presto.common.experimental.auto_gen.ThriftTypeInfo.read0(oprot);
            builder.setTypeInfo(typeInfo);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (typeInfo != null) {
        oprot.writeFieldBegin(TYPE_INFO_FIELD_DESC);
        this.typeInfo.write0(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftHiveTypeLazy {
        private static final ThriftHiveType _DEFAULT = new ThriftHiveType.Builder().build();
    }
    
    public static ThriftHiveType defaultInstance() {
        return  _ThriftHiveTypeLazy._DEFAULT;
    }
}
