/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftExecutionFailureInfo", builder=ThriftExecutionFailureInfo.Builder.class)
public final class ThriftExecutionFailureInfo implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftExecutionFailureInfo(
        @com.facebook.swift.codec.ThriftField(value=1, name="type", requiredness=Requiredness.NONE) final String type,
        @com.facebook.swift.codec.ThriftField(value=2, name="message", requiredness=Requiredness.NONE) final String message,
        @com.facebook.swift.codec.ThriftField(value=3, name="cause", requiredness=Requiredness.OPTIONAL) final com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo cause,
        @com.facebook.swift.codec.ThriftField(value=4, name="suppressed", requiredness=Requiredness.OPTIONAL) final List<com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo> suppressed,
        @com.facebook.swift.codec.ThriftField(value=5, name="stack", requiredness=Requiredness.NONE) final List<String> stack,
        @com.facebook.swift.codec.ThriftField(value=6, name="errorLocation", requiredness=Requiredness.NONE) final com.facebook.presto.common.experimental.auto_gen.ThriftErrorLocation errorLocation,
        @com.facebook.swift.codec.ThriftField(value=7, name="errorCode", requiredness=Requiredness.NONE) final com.facebook.presto.common.experimental.auto_gen.ThriftErrorCode errorCode,
        @com.facebook.swift.codec.ThriftField(value=8, name="remoteHost", requiredness=Requiredness.NONE) final com.facebook.presto.common.experimental.auto_gen.ThriftHostAddress remoteHost,
        @com.facebook.swift.codec.ThriftField(value=9, name="errorCause", requiredness=Requiredness.NONE) final com.facebook.presto.common.experimental.auto_gen.ThriftErrorCause errorCause
    ) {
        this.type = type;
        this.message = message;
        this.cause = cause;
        this.suppressed = suppressed;
        this.stack = stack;
        this.errorLocation = errorLocation;
        this.errorCode = errorCode;
        this.remoteHost = remoteHost;
        this.errorCause = errorCause;
    }
    
    @ThriftConstructor
    protected ThriftExecutionFailureInfo() {
      this.type = null;
      this.message = null;
      this.cause = null;
      this.suppressed = null;
      this.stack = null;
      this.errorLocation = null;
      this.errorCode = null;
      this.remoteHost = null;
      this.errorCause = com.facebook.presto.common.experimental.auto_gen.ThriftErrorCause.fromInteger(0);
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftExecutionFailureInfo other) {
      return new Builder(other);
    }

    public static class Builder {
        private String type = null;
        private String message = null;
        private com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo cause = null;
        private List<com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo> suppressed = null;
        private List<String> stack = null;
        private com.facebook.presto.common.experimental.auto_gen.ThriftErrorLocation errorLocation = null;
        private com.facebook.presto.common.experimental.auto_gen.ThriftErrorCode errorCode = null;
        private com.facebook.presto.common.experimental.auto_gen.ThriftHostAddress remoteHost = null;
        private com.facebook.presto.common.experimental.auto_gen.ThriftErrorCause errorCause = com.facebook.presto.common.experimental.auto_gen.ThriftErrorCause.fromInteger(0);
    
        @com.facebook.swift.codec.ThriftField(value=1, name="type", requiredness=Requiredness.NONE)    public Builder setType(String type) {
            this.type = type;
            return this;
        }
    
        public String getType() { return type; }
    
            @com.facebook.swift.codec.ThriftField(value=2, name="message", requiredness=Requiredness.NONE)    public Builder setMessage(String message) {
            this.message = message;
            return this;
        }
    
        public String getMessage() { return message; }
    
            @com.facebook.swift.codec.ThriftField(value=3, name="cause", requiredness=Requiredness.OPTIONAL)    public Builder setCause(com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo cause) {
            this.cause = cause;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo getCause() { return cause; }
    
            @com.facebook.swift.codec.ThriftField(value=4, name="suppressed", requiredness=Requiredness.OPTIONAL)    public Builder setSuppressed(List<com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo> suppressed) {
            this.suppressed = suppressed;
            return this;
        }
    
        public List<com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo> getSuppressed() { return suppressed; }
    
            @com.facebook.swift.codec.ThriftField(value=5, name="stack", requiredness=Requiredness.NONE)    public Builder setStack(List<String> stack) {
            this.stack = stack;
            return this;
        }
    
        public List<String> getStack() { return stack; }
    
            @com.facebook.swift.codec.ThriftField(value=6, name="errorLocation", requiredness=Requiredness.NONE)    public Builder setErrorLocation(com.facebook.presto.common.experimental.auto_gen.ThriftErrorLocation errorLocation) {
            this.errorLocation = errorLocation;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftErrorLocation getErrorLocation() { return errorLocation; }
    
            @com.facebook.swift.codec.ThriftField(value=7, name="errorCode", requiredness=Requiredness.NONE)    public Builder setErrorCode(com.facebook.presto.common.experimental.auto_gen.ThriftErrorCode errorCode) {
            this.errorCode = errorCode;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftErrorCode getErrorCode() { return errorCode; }
    
            @com.facebook.swift.codec.ThriftField(value=8, name="remoteHost", requiredness=Requiredness.NONE)    public Builder setRemoteHost(com.facebook.presto.common.experimental.auto_gen.ThriftHostAddress remoteHost) {
            this.remoteHost = remoteHost;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftHostAddress getRemoteHost() { return remoteHost; }
    
            @com.facebook.swift.codec.ThriftField(value=9, name="errorCause", requiredness=Requiredness.NONE)    public Builder setErrorCause(com.facebook.presto.common.experimental.auto_gen.ThriftErrorCause errorCause) {
            this.errorCause = errorCause;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftErrorCause getErrorCause() { return errorCause; }
    
        public Builder() { }
        public Builder(ThriftExecutionFailureInfo other) {
            this.type = other.type;
            this.message = other.message;
            this.cause = other.cause;
            this.suppressed = other.suppressed;
            this.stack = other.stack;
            this.errorLocation = other.errorLocation;
            this.errorCode = other.errorCode;
            this.remoteHost = other.remoteHost;
            this.errorCause = other.errorCause;
        }
    
        @ThriftConstructor
        public ThriftExecutionFailureInfo build() {
            ThriftExecutionFailureInfo result = new ThriftExecutionFailureInfo (
                this.type,
                this.message,
                this.cause,
                this.suppressed,
                this.stack,
                this.errorLocation,
                this.errorCode,
                this.remoteHost,
                this.errorCause
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftExecutionFailureInfo");
    private final String type;
    public static final int _TYPE = 1;
    private static final TField TYPE_FIELD_DESC = new TField("type", TType.STRING, (short)1);
        private final String message;
    public static final int _MESSAGE = 2;
    private static final TField MESSAGE_FIELD_DESC = new TField("message", TType.STRING, (short)2);
        private final com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo cause;
    public static final int _CAUSE = 3;
    private static final TField CAUSE_FIELD_DESC = new TField("cause", TType.STRUCT, (short)3);
        private final List<com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo> suppressed;
    public static final int _SUPPRESSED = 4;
    private static final TField SUPPRESSED_FIELD_DESC = new TField("suppressed", TType.LIST, (short)4);
        private final List<String> stack;
    public static final int _STACK = 5;
    private static final TField STACK_FIELD_DESC = new TField("stack", TType.LIST, (short)5);
        private final com.facebook.presto.common.experimental.auto_gen.ThriftErrorLocation errorLocation;
    public static final int _ERRORLOCATION = 6;
    private static final TField ERROR_LOCATION_FIELD_DESC = new TField("errorLocation", TType.STRUCT, (short)6);
        private final com.facebook.presto.common.experimental.auto_gen.ThriftErrorCode errorCode;
    public static final int _ERRORCODE = 7;
    private static final TField ERROR_CODE_FIELD_DESC = new TField("errorCode", TType.STRUCT, (short)7);
        private final com.facebook.presto.common.experimental.auto_gen.ThriftHostAddress remoteHost;
    public static final int _REMOTEHOST = 8;
    private static final TField REMOTE_HOST_FIELD_DESC = new TField("remoteHost", TType.STRUCT, (short)8);
        private final com.facebook.presto.common.experimental.auto_gen.ThriftErrorCause errorCause;
    public static final int _ERRORCAUSE = 9;
    private static final TField ERROR_CAUSE_FIELD_DESC = new TField("errorCause", TType.I32, (short)9);
    static {
      NAMES_TO_IDS.put("type", 1);
      THRIFT_NAMES_TO_IDS.put("type", 1);
      FIELD_METADATA.put(1, TYPE_FIELD_DESC);
      NAMES_TO_IDS.put("message", 2);
      THRIFT_NAMES_TO_IDS.put("message", 2);
      FIELD_METADATA.put(2, MESSAGE_FIELD_DESC);
      NAMES_TO_IDS.put("cause", 3);
      THRIFT_NAMES_TO_IDS.put("cause", 3);
      FIELD_METADATA.put(3, CAUSE_FIELD_DESC);
      NAMES_TO_IDS.put("suppressed", 4);
      THRIFT_NAMES_TO_IDS.put("suppressed", 4);
      FIELD_METADATA.put(4, SUPPRESSED_FIELD_DESC);
      NAMES_TO_IDS.put("stack", 5);
      THRIFT_NAMES_TO_IDS.put("stack", 5);
      FIELD_METADATA.put(5, STACK_FIELD_DESC);
      NAMES_TO_IDS.put("errorLocation", 6);
      THRIFT_NAMES_TO_IDS.put("errorLocation", 6);
      FIELD_METADATA.put(6, ERROR_LOCATION_FIELD_DESC);
      NAMES_TO_IDS.put("errorCode", 7);
      THRIFT_NAMES_TO_IDS.put("errorCode", 7);
      FIELD_METADATA.put(7, ERROR_CODE_FIELD_DESC);
      NAMES_TO_IDS.put("remoteHost", 8);
      THRIFT_NAMES_TO_IDS.put("remoteHost", 8);
      FIELD_METADATA.put(8, REMOTE_HOST_FIELD_DESC);
      NAMES_TO_IDS.put("errorCause", 9);
      THRIFT_NAMES_TO_IDS.put("errorCause", 9);
      FIELD_METADATA.put(9, ERROR_CAUSE_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="type", requiredness=Requiredness.NONE)
    public String getType() { return type; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=2, name="message", requiredness=Requiredness.NONE)
    public String getMessage() { return message; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=3, name="cause", requiredness=Requiredness.OPTIONAL)
    public com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo getCause() { return cause; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=4, name="suppressed", requiredness=Requiredness.OPTIONAL)
    public List<com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo> getSuppressed() { return suppressed; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=5, name="stack", requiredness=Requiredness.NONE)
    public List<String> getStack() { return stack; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=6, name="errorLocation", requiredness=Requiredness.NONE)
    public com.facebook.presto.common.experimental.auto_gen.ThriftErrorLocation getErrorLocation() { return errorLocation; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=7, name="errorCode", requiredness=Requiredness.NONE)
    public com.facebook.presto.common.experimental.auto_gen.ThriftErrorCode getErrorCode() { return errorCode; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=8, name="remoteHost", requiredness=Requiredness.NONE)
    public com.facebook.presto.common.experimental.auto_gen.ThriftHostAddress getRemoteHost() { return remoteHost; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=9, name="errorCause", requiredness=Requiredness.NONE)
    public com.facebook.presto.common.experimental.auto_gen.ThriftErrorCause getErrorCause() { return errorCause; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("type", type);
        helper.add("message", message);
        helper.add("cause", cause);
        helper.add("suppressed", suppressed);
        helper.add("stack", stack);
        helper.add("errorLocation", errorLocation);
        helper.add("errorCode", errorCode);
        helper.add("remoteHost", remoteHost);
        helper.add("errorCause", errorCause);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftExecutionFailureInfo other = (ThriftExecutionFailureInfo)o;
    
        return
            Objects.equals(type, other.type) &&
            Objects.equals(message, other.message) &&
            Objects.equals(cause, other.cause) &&
            Objects.equals(suppressed, other.suppressed) &&
            Objects.equals(stack, other.stack) &&
            Objects.equals(errorLocation, other.errorLocation) &&
            Objects.equals(errorCode, other.errorCode) &&
            Objects.equals(remoteHost, other.remoteHost) &&
            Objects.equals(errorCause, other.errorCause) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            type,
            message,
            cause,
            suppressed,
            stack,
            errorLocation,
            errorCode,
            remoteHost,
            errorCause
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftExecutionFailureInfo> asReader() {
      return ThriftExecutionFailureInfo::read0;
    }
    
    public static ThriftExecutionFailureInfo read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftExecutionFailureInfo.NAMES_TO_IDS, ThriftExecutionFailureInfo.THRIFT_NAMES_TO_IDS, ThriftExecutionFailureInfo.FIELD_METADATA);
      ThriftExecutionFailureInfo.Builder builder = new ThriftExecutionFailureInfo.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _TYPE:
          if (__field.type == TType.STRING) {
            String type = oprot.readString();
            builder.setType(type);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _MESSAGE:
          if (__field.type == TType.STRING) {
            String message = oprot.readString();
            builder.setMessage(message);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _CAUSE:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo cause = com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo.read0(oprot);
            builder.setCause(cause);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _SUPPRESSED:
          if (__field.type == TType.LIST) {
            List<com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo> suppressed;
                {
                TList _list = oprot.readListBegin();
                suppressed = new ArrayList<com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo>(Math.max(0, _list.size));
                for (int _i = 0; (_list.size < 0) ? oprot.peekList() : (_i < _list.size); _i++) {
                    
                    com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo _value1 = com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo.read0(oprot);
                    suppressed.add(_value1);
                }
                oprot.readListEnd();
                }
            builder.setSuppressed(suppressed);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _STACK:
          if (__field.type == TType.LIST) {
            List<String> stack;
                {
                TList _list = oprot.readListBegin();
                stack = new ArrayList<String>(Math.max(0, _list.size));
                for (int _i = 0; (_list.size < 0) ? oprot.peekList() : (_i < _list.size); _i++) {
                    
                    String _value1 = oprot.readString();
                    stack.add(_value1);
                }
                oprot.readListEnd();
                }
            builder.setStack(stack);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _ERRORLOCATION:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftErrorLocation errorLocation = com.facebook.presto.common.experimental.auto_gen.ThriftErrorLocation.read0(oprot);
            builder.setErrorLocation(errorLocation);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _ERRORCODE:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftErrorCode errorCode = com.facebook.presto.common.experimental.auto_gen.ThriftErrorCode.read0(oprot);
            builder.setErrorCode(errorCode);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _REMOTEHOST:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftHostAddress remoteHost = com.facebook.presto.common.experimental.auto_gen.ThriftHostAddress.read0(oprot);
            builder.setRemoteHost(remoteHost);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _ERRORCAUSE:
          if (__field.type == TType.I32) {
            com.facebook.presto.common.experimental.auto_gen.ThriftErrorCause errorCause = com.facebook.presto.common.experimental.auto_gen.ThriftErrorCause.fromInteger(oprot.readI32());
            builder.setErrorCause(errorCause);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeString(this.type);
        oprot.writeFieldEnd();
      }
      if (message != null) {
        oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
        oprot.writeString(this.message);
        oprot.writeFieldEnd();
      }
      if (cause != null) {
        oprot.writeFieldBegin(CAUSE_FIELD_DESC);
        this.cause.write0(oprot);
        oprot.writeFieldEnd();
      }
      if (suppressed != null) {
        oprot.writeFieldBegin(SUPPRESSED_FIELD_DESC);
        List<com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo>  _iter0 = suppressed;
        oprot.writeListBegin(new TList(TType.STRUCT, _iter0.size()));
            for (com.facebook.presto.common.experimental.auto_gen.ThriftExecutionFailureInfo _iter1 : _iter0) {
              _iter1.write0(oprot);
            }
            oprot.writeListEnd();
        oprot.writeFieldEnd();
      }
      if (stack != null) {
        oprot.writeFieldBegin(STACK_FIELD_DESC);
        List<String> _iter0 = stack;
        oprot.writeListBegin(new TList(TType.STRING, _iter0.size()));
            for (String _iter1 : _iter0) {
              oprot.writeString(_iter1);
            }
            oprot.writeListEnd();
        oprot.writeFieldEnd();
      }
      if (errorLocation != null) {
        oprot.writeFieldBegin(ERROR_LOCATION_FIELD_DESC);
        this.errorLocation.write0(oprot);
        oprot.writeFieldEnd();
      }
      if (errorCode != null) {
        oprot.writeFieldBegin(ERROR_CODE_FIELD_DESC);
        this.errorCode.write0(oprot);
        oprot.writeFieldEnd();
      }
      if (remoteHost != null) {
        oprot.writeFieldBegin(REMOTE_HOST_FIELD_DESC);
        this.remoteHost.write0(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ERROR_CAUSE_FIELD_DESC);
      oprot.writeI32(this.errorCause == null ? 0 : com.facebook.thrift.util.EnumUtil.getValue(this.errorCause));
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftExecutionFailureInfoLazy {
        private static final ThriftExecutionFailureInfo _DEFAULT = new ThriftExecutionFailureInfo.Builder().build();
    }
    
    public static ThriftExecutionFailureInfo defaultInstance() {
        return  _ThriftExecutionFailureInfoLazy._DEFAULT;
    }
}
