/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftOrderingScheme", builder=ThriftOrderingScheme.Builder.class)
public final class ThriftOrderingScheme implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftOrderingScheme(
        @com.facebook.swift.codec.ThriftField(value=1, name="orderBy", requiredness=Requiredness.NONE) final List<com.facebook.presto.common.experimental.auto_gen.ThriftOrdering> orderBy
    ) {
        this.orderBy = orderBy;
    }
    
    @ThriftConstructor
    protected ThriftOrderingScheme() {
      this.orderBy = null;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftOrderingScheme other) {
      return new Builder(other);
    }

    public static class Builder {
        private List<com.facebook.presto.common.experimental.auto_gen.ThriftOrdering> orderBy = null;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="orderBy", requiredness=Requiredness.NONE)    public Builder setOrderBy(List<com.facebook.presto.common.experimental.auto_gen.ThriftOrdering> orderBy) {
            this.orderBy = orderBy;
            return this;
        }
    
        public List<com.facebook.presto.common.experimental.auto_gen.ThriftOrdering> getOrderBy() { return orderBy; }
    
        public Builder() { }
        public Builder(ThriftOrderingScheme other) {
            this.orderBy = other.orderBy;
        }
    
        @ThriftConstructor
        public ThriftOrderingScheme build() {
            ThriftOrderingScheme result = new ThriftOrderingScheme (
                this.orderBy
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftOrderingScheme");
    private final List<com.facebook.presto.common.experimental.auto_gen.ThriftOrdering> orderBy;
    public static final int _ORDERBY = 1;
    private static final TField ORDER_BY_FIELD_DESC = new TField("orderBy", TType.LIST, (short)1);
    static {
      NAMES_TO_IDS.put("orderBy", 1);
      THRIFT_NAMES_TO_IDS.put("orderBy", 1);
      FIELD_METADATA.put(1, ORDER_BY_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="orderBy", requiredness=Requiredness.NONE)
    public List<com.facebook.presto.common.experimental.auto_gen.ThriftOrdering> getOrderBy() { return orderBy; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("orderBy", orderBy);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftOrderingScheme other = (ThriftOrderingScheme)o;
    
        return
            Objects.equals(orderBy, other.orderBy) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            orderBy
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftOrderingScheme> asReader() {
      return ThriftOrderingScheme::read0;
    }
    
    public static ThriftOrderingScheme read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftOrderingScheme.NAMES_TO_IDS, ThriftOrderingScheme.THRIFT_NAMES_TO_IDS, ThriftOrderingScheme.FIELD_METADATA);
      ThriftOrderingScheme.Builder builder = new ThriftOrderingScheme.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _ORDERBY:
          if (__field.type == TType.LIST) {
            List<com.facebook.presto.common.experimental.auto_gen.ThriftOrdering> orderBy;
                {
                TList _list = oprot.readListBegin();
                orderBy = new ArrayList<com.facebook.presto.common.experimental.auto_gen.ThriftOrdering>(Math.max(0, _list.size));
                for (int _i = 0; (_list.size < 0) ? oprot.peekList() : (_i < _list.size); _i++) {
                    
                    com.facebook.presto.common.experimental.auto_gen.ThriftOrdering _value1 = com.facebook.presto.common.experimental.auto_gen.ThriftOrdering.read0(oprot);
                    orderBy.add(_value1);
                }
                oprot.readListEnd();
                }
            builder.setOrderBy(orderBy);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (orderBy != null) {
        oprot.writeFieldBegin(ORDER_BY_FIELD_DESC);
        List<com.facebook.presto.common.experimental.auto_gen.ThriftOrdering> _iter0 = orderBy;
        oprot.writeListBegin(new TList(TType.STRUCT, _iter0.size()));
            for (com.facebook.presto.common.experimental.auto_gen.ThriftOrdering _iter1 : _iter0) {
              _iter1.write0(oprot);
            }
            oprot.writeListEnd();
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftOrderingSchemeLazy {
        private static final ThriftOrderingScheme _DEFAULT = new ThriftOrderingScheme.Builder().build();
    }
    
    public static ThriftOrderingScheme defaultInstance() {
        return  _ThriftOrderingSchemeLazy._DEFAULT;
    }
}
