/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftInputReferenceExpression", builder=ThriftInputReferenceExpression.Builder.class)
public final class ThriftInputReferenceExpression implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftInputReferenceExpression(
        @com.facebook.swift.codec.ThriftField(value=1, name="sourceLocation", requiredness=Requiredness.OPTIONAL) final com.facebook.presto.common.experimental.auto_gen.ThriftSourceLocation sourceLocation,
        @com.facebook.swift.codec.ThriftField(value=2, name="field", requiredness=Requiredness.NONE) final int field,
        @com.facebook.swift.codec.ThriftField(value=3, name="type", requiredness=Requiredness.NONE) final com.facebook.presto.common.experimental.auto_gen.ThriftType type
    ) {
        this.sourceLocation = sourceLocation;
        this.field = field;
        this.type = type;
    }
    
    @ThriftConstructor
    protected ThriftInputReferenceExpression() {
      this.sourceLocation = null;
      this.field = 0;
      this.type = null;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftInputReferenceExpression other) {
      return new Builder(other);
    }

    public static class Builder {
        private com.facebook.presto.common.experimental.auto_gen.ThriftSourceLocation sourceLocation = null;
        private int field = 0;
        private com.facebook.presto.common.experimental.auto_gen.ThriftType type = null;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="sourceLocation", requiredness=Requiredness.OPTIONAL)    public Builder setSourceLocation(com.facebook.presto.common.experimental.auto_gen.ThriftSourceLocation sourceLocation) {
            this.sourceLocation = sourceLocation;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftSourceLocation getSourceLocation() { return sourceLocation; }
    
            @com.facebook.swift.codec.ThriftField(value=2, name="field", requiredness=Requiredness.NONE)    public Builder setField(int field) {
            this.field = field;
            return this;
        }
    
        public int getField() { return field; }
    
            @com.facebook.swift.codec.ThriftField(value=3, name="type", requiredness=Requiredness.NONE)    public Builder setType(com.facebook.presto.common.experimental.auto_gen.ThriftType type) {
            this.type = type;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftType getType() { return type; }
    
        public Builder() { }
        public Builder(ThriftInputReferenceExpression other) {
            this.sourceLocation = other.sourceLocation;
            this.field = other.field;
            this.type = other.type;
        }
    
        @ThriftConstructor
        public ThriftInputReferenceExpression build() {
            ThriftInputReferenceExpression result = new ThriftInputReferenceExpression (
                this.sourceLocation,
                this.field,
                this.type
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftInputReferenceExpression");
    private final com.facebook.presto.common.experimental.auto_gen.ThriftSourceLocation sourceLocation;
    public static final int _SOURCELOCATION = 1;
    private static final TField SOURCE_LOCATION_FIELD_DESC = new TField("sourceLocation", TType.STRUCT, (short)1);
        private final int field;
    public static final int _FIELD = 2;
    private static final TField FIELD_FIELD_DESC = new TField("field", TType.I32, (short)2);
        private final com.facebook.presto.common.experimental.auto_gen.ThriftType type;
    public static final int _TYPE = 3;
    private static final TField TYPE_FIELD_DESC = new TField("type", TType.STRUCT, (short)3);
    static {
      NAMES_TO_IDS.put("sourceLocation", 1);
      THRIFT_NAMES_TO_IDS.put("sourceLocation", 1);
      FIELD_METADATA.put(1, SOURCE_LOCATION_FIELD_DESC);
      NAMES_TO_IDS.put("field", 2);
      THRIFT_NAMES_TO_IDS.put("field", 2);
      FIELD_METADATA.put(2, FIELD_FIELD_DESC);
      NAMES_TO_IDS.put("type", 3);
      THRIFT_NAMES_TO_IDS.put("type", 3);
      FIELD_METADATA.put(3, TYPE_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="sourceLocation", requiredness=Requiredness.OPTIONAL)
    public com.facebook.presto.common.experimental.auto_gen.ThriftSourceLocation getSourceLocation() { return sourceLocation; }

    
    
    @com.facebook.swift.codec.ThriftField(value=2, name="field", requiredness=Requiredness.NONE)
    public int getField() { return field; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=3, name="type", requiredness=Requiredness.NONE)
    public com.facebook.presto.common.experimental.auto_gen.ThriftType getType() { return type; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("sourceLocation", sourceLocation);
        helper.add("field", field);
        helper.add("type", type);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftInputReferenceExpression other = (ThriftInputReferenceExpression)o;
    
        return
            Objects.equals(sourceLocation, other.sourceLocation) &&
            Objects.equals(field, other.field) &&
            Objects.equals(type, other.type) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            sourceLocation,
            field,
            type
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftInputReferenceExpression> asReader() {
      return ThriftInputReferenceExpression::read0;
    }
    
    public static ThriftInputReferenceExpression read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftInputReferenceExpression.NAMES_TO_IDS, ThriftInputReferenceExpression.THRIFT_NAMES_TO_IDS, ThriftInputReferenceExpression.FIELD_METADATA);
      ThriftInputReferenceExpression.Builder builder = new ThriftInputReferenceExpression.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _SOURCELOCATION:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftSourceLocation sourceLocation = com.facebook.presto.common.experimental.auto_gen.ThriftSourceLocation.read0(oprot);
            builder.setSourceLocation(sourceLocation);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _FIELD:
          if (__field.type == TType.I32) {
            int field = oprot.readI32();
            builder.setField(field);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _TYPE:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftType type = com.facebook.presto.common.experimental.auto_gen.ThriftType.read0(oprot);
            builder.setType(type);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (sourceLocation != null) {
        oprot.writeFieldBegin(SOURCE_LOCATION_FIELD_DESC);
        this.sourceLocation.write0(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(FIELD_FIELD_DESC);
      oprot.writeI32(this.field);
      oprot.writeFieldEnd();
      if (type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        this.type.write0(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftInputReferenceExpressionLazy {
        private static final ThriftInputReferenceExpression _DEFAULT = new ThriftInputReferenceExpression.Builder().build();
    }
    
    public static ThriftInputReferenceExpression defaultInstance() {
        return  _ThriftInputReferenceExpressionLazy._DEFAULT;
    }
}
