/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftListOfStringAsKey", builder=ThriftListOfStringAsKey.Builder.class)
public final class ThriftListOfStringAsKey implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftListOfStringAsKey(
        @com.facebook.swift.codec.ThriftField(value=1, name="key", requiredness=Requiredness.NONE) final List<String> key
    ) {
        this.key = key;
    }
    
    @ThriftConstructor
    protected ThriftListOfStringAsKey() {
      this.key = null;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftListOfStringAsKey other) {
      return new Builder(other);
    }

    public static class Builder {
        private List<String> key = null;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="key", requiredness=Requiredness.NONE)    public Builder setKey(List<String> key) {
            this.key = key;
            return this;
        }
    
        public List<String> getKey() { return key; }
    
        public Builder() { }
        public Builder(ThriftListOfStringAsKey other) {
            this.key = other.key;
        }
    
        @ThriftConstructor
        public ThriftListOfStringAsKey build() {
            ThriftListOfStringAsKey result = new ThriftListOfStringAsKey (
                this.key
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftListOfStringAsKey");
    private final List<String> key;
    public static final int _KEY = 1;
    private static final TField KEY_FIELD_DESC = new TField("key", TType.LIST, (short)1);
    static {
      NAMES_TO_IDS.put("key", 1);
      THRIFT_NAMES_TO_IDS.put("key", 1);
      FIELD_METADATA.put(1, KEY_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="key", requiredness=Requiredness.NONE)
    public List<String> getKey() { return key; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("key", key);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftListOfStringAsKey other = (ThriftListOfStringAsKey)o;
    
        return
            Objects.equals(key, other.key) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            key
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftListOfStringAsKey> asReader() {
      return ThriftListOfStringAsKey::read0;
    }
    
    public static ThriftListOfStringAsKey read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftListOfStringAsKey.NAMES_TO_IDS, ThriftListOfStringAsKey.THRIFT_NAMES_TO_IDS, ThriftListOfStringAsKey.FIELD_METADATA);
      ThriftListOfStringAsKey.Builder builder = new ThriftListOfStringAsKey.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _KEY:
          if (__field.type == TType.LIST) {
            List<String> key;
                {
                TList _list = oprot.readListBegin();
                key = new ArrayList<String>(Math.max(0, _list.size));
                for (int _i = 0; (_list.size < 0) ? oprot.peekList() : (_i < _list.size); _i++) {
                    
                    String _value1 = oprot.readString();
                    key.add(_value1);
                }
                oprot.readListEnd();
                }
            builder.setKey(key);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (key != null) {
        oprot.writeFieldBegin(KEY_FIELD_DESC);
        List<String> _iter0 = key;
        oprot.writeListBegin(new TList(TType.STRING, _iter0.size()));
            for (String _iter1 : _iter0) {
              oprot.writeString(_iter1);
            }
            oprot.writeListEnd();
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftListOfStringAsKeyLazy {
        private static final ThriftListOfStringAsKey _DEFAULT = new ThriftListOfStringAsKey.Builder().build();
    }
    
    public static ThriftListOfStringAsKey defaultInstance() {
        return  _ThriftListOfStringAsKeyLazy._DEFAULT;
    }
}
