/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftIntegerType", builder=ThriftIntegerType.Builder.class)
public final class ThriftIntegerType implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftIntegerType(
    ) {
    }
    
    

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftIntegerType other) {
      return new Builder(other);
    }

    public static class Builder {
    
    public Builder() { }
        public Builder(ThriftIntegerType other) {
        }
    
        @ThriftConstructor
        public ThriftIntegerType build() {
            ThriftIntegerType result = new ThriftIntegerType (
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftIntegerType");
static {
    }
    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftIntegerType other = (ThriftIntegerType)o;
    
        return
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftIntegerType> asReader() {
      return ThriftIntegerType::read0;
    }
    
    public static ThriftIntegerType read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftIntegerType.NAMES_TO_IDS, ThriftIntegerType.THRIFT_NAMES_TO_IDS, ThriftIntegerType.FIELD_METADATA);
      ThriftIntegerType.Builder builder = new ThriftIntegerType.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftIntegerTypeLazy {
        private static final ThriftIntegerType _DEFAULT = new ThriftIntegerType.Builder().build();
    }
    
    public static ThriftIntegerType defaultInstance() {
        return  _ThriftIntegerTypeLazy._DEFAULT;
    }
}
