/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftCreateHandle", builder=ThriftCreateHandle.Builder.class)
public final class ThriftCreateHandle implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftCreateHandle(
        @com.facebook.swift.codec.ThriftField(value=1, name="handle", requiredness=Requiredness.NONE) final com.facebook.presto.common.experimental.auto_gen.ThriftOutputTableHandle handle,
        @com.facebook.swift.codec.ThriftField(value=2, name="schemaTableName", requiredness=Requiredness.NONE) final com.facebook.presto.common.experimental.auto_gen.ThriftSchemaTableName schemaTableName
    ) {
        this.handle = handle;
        this.schemaTableName = schemaTableName;
    }
    
    @ThriftConstructor
    protected ThriftCreateHandle() {
      this.handle = null;
      this.schemaTableName = null;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftCreateHandle other) {
      return new Builder(other);
    }

    public static class Builder {
        private com.facebook.presto.common.experimental.auto_gen.ThriftOutputTableHandle handle = null;
        private com.facebook.presto.common.experimental.auto_gen.ThriftSchemaTableName schemaTableName = null;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="handle", requiredness=Requiredness.NONE)    public Builder setHandle(com.facebook.presto.common.experimental.auto_gen.ThriftOutputTableHandle handle) {
            this.handle = handle;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftOutputTableHandle getHandle() { return handle; }
    
            @com.facebook.swift.codec.ThriftField(value=2, name="schemaTableName", requiredness=Requiredness.NONE)    public Builder setSchemaTableName(com.facebook.presto.common.experimental.auto_gen.ThriftSchemaTableName schemaTableName) {
            this.schemaTableName = schemaTableName;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftSchemaTableName getSchemaTableName() { return schemaTableName; }
    
        public Builder() { }
        public Builder(ThriftCreateHandle other) {
            this.handle = other.handle;
            this.schemaTableName = other.schemaTableName;
        }
    
        @ThriftConstructor
        public ThriftCreateHandle build() {
            ThriftCreateHandle result = new ThriftCreateHandle (
                this.handle,
                this.schemaTableName
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftCreateHandle");
    private final com.facebook.presto.common.experimental.auto_gen.ThriftOutputTableHandle handle;
    public static final int _HANDLE = 1;
    private static final TField HANDLE_FIELD_DESC = new TField("handle", TType.STRUCT, (short)1);
        private final com.facebook.presto.common.experimental.auto_gen.ThriftSchemaTableName schemaTableName;
    public static final int _SCHEMATABLENAME = 2;
    private static final TField SCHEMA_TABLE_NAME_FIELD_DESC = new TField("schemaTableName", TType.STRUCT, (short)2);
    static {
      NAMES_TO_IDS.put("handle", 1);
      THRIFT_NAMES_TO_IDS.put("handle", 1);
      FIELD_METADATA.put(1, HANDLE_FIELD_DESC);
      NAMES_TO_IDS.put("schemaTableName", 2);
      THRIFT_NAMES_TO_IDS.put("schemaTableName", 2);
      FIELD_METADATA.put(2, SCHEMA_TABLE_NAME_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="handle", requiredness=Requiredness.NONE)
    public com.facebook.presto.common.experimental.auto_gen.ThriftOutputTableHandle getHandle() { return handle; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=2, name="schemaTableName", requiredness=Requiredness.NONE)
    public com.facebook.presto.common.experimental.auto_gen.ThriftSchemaTableName getSchemaTableName() { return schemaTableName; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("handle", handle);
        helper.add("schemaTableName", schemaTableName);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftCreateHandle other = (ThriftCreateHandle)o;
    
        return
            Objects.equals(handle, other.handle) &&
            Objects.equals(schemaTableName, other.schemaTableName) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            handle,
            schemaTableName
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftCreateHandle> asReader() {
      return ThriftCreateHandle::read0;
    }
    
    public static ThriftCreateHandle read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftCreateHandle.NAMES_TO_IDS, ThriftCreateHandle.THRIFT_NAMES_TO_IDS, ThriftCreateHandle.FIELD_METADATA);
      ThriftCreateHandle.Builder builder = new ThriftCreateHandle.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _HANDLE:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftOutputTableHandle handle = com.facebook.presto.common.experimental.auto_gen.ThriftOutputTableHandle.read0(oprot);
            builder.setHandle(handle);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _SCHEMATABLENAME:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftSchemaTableName schemaTableName = com.facebook.presto.common.experimental.auto_gen.ThriftSchemaTableName.read0(oprot);
            builder.setSchemaTableName(schemaTableName);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (handle != null) {
        oprot.writeFieldBegin(HANDLE_FIELD_DESC);
        this.handle.write0(oprot);
        oprot.writeFieldEnd();
      }
      if (schemaTableName != null) {
        oprot.writeFieldBegin(SCHEMA_TABLE_NAME_FIELD_DESC);
        this.schemaTableName.write0(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftCreateHandleLazy {
        private static final ThriftCreateHandle _DEFAULT = new ThriftCreateHandle.Builder().build();
    }
    
    public static ThriftCreateHandle defaultInstance() {
        return  _ThriftCreateHandleLazy._DEFAULT;
    }
}
