/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftEncryptionInformation", builder=ThriftEncryptionInformation.Builder.class)
public final class ThriftEncryptionInformation implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftEncryptionInformation(
        @com.facebook.swift.codec.ThriftField(value=1, name="dwrfEncryptionMetadata", requiredness=Requiredness.OPTIONAL) final com.facebook.presto.common.experimental.auto_gen.ThriftDwrfEncryptionMetadata dwrfEncryptionMetadata
    ) {
        this.dwrfEncryptionMetadata = dwrfEncryptionMetadata;
    }
    
    @ThriftConstructor
    protected ThriftEncryptionInformation() {
      this.dwrfEncryptionMetadata = null;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftEncryptionInformation other) {
      return new Builder(other);
    }

    public static class Builder {
        private com.facebook.presto.common.experimental.auto_gen.ThriftDwrfEncryptionMetadata dwrfEncryptionMetadata = null;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="dwrfEncryptionMetadata", requiredness=Requiredness.OPTIONAL)    public Builder setDwrfEncryptionMetadata(com.facebook.presto.common.experimental.auto_gen.ThriftDwrfEncryptionMetadata dwrfEncryptionMetadata) {
            this.dwrfEncryptionMetadata = dwrfEncryptionMetadata;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftDwrfEncryptionMetadata getDwrfEncryptionMetadata() { return dwrfEncryptionMetadata; }
    
        public Builder() { }
        public Builder(ThriftEncryptionInformation other) {
            this.dwrfEncryptionMetadata = other.dwrfEncryptionMetadata;
        }
    
        @ThriftConstructor
        public ThriftEncryptionInformation build() {
            ThriftEncryptionInformation result = new ThriftEncryptionInformation (
                this.dwrfEncryptionMetadata
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftEncryptionInformation");
    private final com.facebook.presto.common.experimental.auto_gen.ThriftDwrfEncryptionMetadata dwrfEncryptionMetadata;
    public static final int _DWRFENCRYPTIONMETADATA = 1;
    private static final TField DWRF_ENCRYPTION_METADATA_FIELD_DESC = new TField("dwrfEncryptionMetadata", TType.STRUCT, (short)1);
    static {
      NAMES_TO_IDS.put("dwrfEncryptionMetadata", 1);
      THRIFT_NAMES_TO_IDS.put("dwrfEncryptionMetadata", 1);
      FIELD_METADATA.put(1, DWRF_ENCRYPTION_METADATA_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="dwrfEncryptionMetadata", requiredness=Requiredness.OPTIONAL)
    public com.facebook.presto.common.experimental.auto_gen.ThriftDwrfEncryptionMetadata getDwrfEncryptionMetadata() { return dwrfEncryptionMetadata; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("dwrfEncryptionMetadata", dwrfEncryptionMetadata);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftEncryptionInformation other = (ThriftEncryptionInformation)o;
    
        return
            Objects.equals(dwrfEncryptionMetadata, other.dwrfEncryptionMetadata) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            dwrfEncryptionMetadata
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftEncryptionInformation> asReader() {
      return ThriftEncryptionInformation::read0;
    }
    
    public static ThriftEncryptionInformation read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftEncryptionInformation.NAMES_TO_IDS, ThriftEncryptionInformation.THRIFT_NAMES_TO_IDS, ThriftEncryptionInformation.FIELD_METADATA);
      ThriftEncryptionInformation.Builder builder = new ThriftEncryptionInformation.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _DWRFENCRYPTIONMETADATA:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftDwrfEncryptionMetadata dwrfEncryptionMetadata = com.facebook.presto.common.experimental.auto_gen.ThriftDwrfEncryptionMetadata.read0(oprot);
            builder.setDwrfEncryptionMetadata(dwrfEncryptionMetadata);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (dwrfEncryptionMetadata != null) {
        oprot.writeFieldBegin(DWRF_ENCRYPTION_METADATA_FIELD_DESC);
        this.dwrfEncryptionMetadata.write0(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftEncryptionInformationLazy {
        private static final ThriftEncryptionInformation _DEFAULT = new ThriftEncryptionInformation.Builder().build();
    }
    
    public static ThriftEncryptionInformation defaultInstance() {
        return  _ThriftEncryptionInformationLazy._DEFAULT;
    }
}
