/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftLongVariableConstraint", builder=ThriftLongVariableConstraint.Builder.class)
public final class ThriftLongVariableConstraint implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftLongVariableConstraint(
        @com.facebook.swift.codec.ThriftField(value=1, name="name", requiredness=Requiredness.NONE) final String name,
        @com.facebook.swift.codec.ThriftField(value=2, name="expression", requiredness=Requiredness.NONE) final String expression
    ) {
        this.name = name;
        this.expression = expression;
    }
    
    @ThriftConstructor
    protected ThriftLongVariableConstraint() {
      this.name = null;
      this.expression = null;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftLongVariableConstraint other) {
      return new Builder(other);
    }

    public static class Builder {
        private String name = null;
        private String expression = null;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="name", requiredness=Requiredness.NONE)    public Builder setName(String name) {
            this.name = name;
            return this;
        }
    
        public String getName() { return name; }
    
            @com.facebook.swift.codec.ThriftField(value=2, name="expression", requiredness=Requiredness.NONE)    public Builder setExpression(String expression) {
            this.expression = expression;
            return this;
        }
    
        public String getExpression() { return expression; }
    
        public Builder() { }
        public Builder(ThriftLongVariableConstraint other) {
            this.name = other.name;
            this.expression = other.expression;
        }
    
        @ThriftConstructor
        public ThriftLongVariableConstraint build() {
            ThriftLongVariableConstraint result = new ThriftLongVariableConstraint (
                this.name,
                this.expression
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftLongVariableConstraint");
    private final String name;
    public static final int _NAME = 1;
    private static final TField NAME_FIELD_DESC = new TField("name", TType.STRING, (short)1);
        private final String expression;
    public static final int _EXPRESSION = 2;
    private static final TField EXPRESSION_FIELD_DESC = new TField("expression", TType.STRING, (short)2);
    static {
      NAMES_TO_IDS.put("name", 1);
      THRIFT_NAMES_TO_IDS.put("name", 1);
      FIELD_METADATA.put(1, NAME_FIELD_DESC);
      NAMES_TO_IDS.put("expression", 2);
      THRIFT_NAMES_TO_IDS.put("expression", 2);
      FIELD_METADATA.put(2, EXPRESSION_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="name", requiredness=Requiredness.NONE)
    public String getName() { return name; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=2, name="expression", requiredness=Requiredness.NONE)
    public String getExpression() { return expression; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("name", name);
        helper.add("expression", expression);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftLongVariableConstraint other = (ThriftLongVariableConstraint)o;
    
        return
            Objects.equals(name, other.name) &&
            Objects.equals(expression, other.expression) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            name,
            expression
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftLongVariableConstraint> asReader() {
      return ThriftLongVariableConstraint::read0;
    }
    
    public static ThriftLongVariableConstraint read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftLongVariableConstraint.NAMES_TO_IDS, ThriftLongVariableConstraint.THRIFT_NAMES_TO_IDS, ThriftLongVariableConstraint.FIELD_METADATA);
      ThriftLongVariableConstraint.Builder builder = new ThriftLongVariableConstraint.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _NAME:
          if (__field.type == TType.STRING) {
            String name = oprot.readString();
            builder.setName(name);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _EXPRESSION:
          if (__field.type == TType.STRING) {
            String expression = oprot.readString();
            builder.setExpression(expression);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(this.name);
        oprot.writeFieldEnd();
      }
      if (expression != null) {
        oprot.writeFieldBegin(EXPRESSION_FIELD_DESC);
        oprot.writeString(this.expression);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftLongVariableConstraintLazy {
        private static final ThriftLongVariableConstraint _DEFAULT = new ThriftLongVariableConstraint.Builder().build();
    }
    
    public static ThriftLongVariableConstraint defaultInstance() {
        return  _ThriftLongVariableConstraintLazy._DEFAULT;
    }
}
