/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import org.apache.fbthrift.TException;
import org.apache.fbthrift.protocol.TProtocol;

@SwiftGenerated
public enum ThriftOrder implements com.facebook.thrift.enums.BaseEnum, com.facebook.thrift.payload.ThriftSerializable {
    ASCENDING(0),
    DESCENDING(1);

    private final int value;

    ThriftOrder(int value) {
        this.value = value;
    }

    @ThriftEnumValue
    public int getValue() {
        return value;
    }

    public static ThriftOrder fromInteger(int n) {
        switch (n) {
        case 0:
            return ASCENDING;
        case 1:
            return DESCENDING;
        default:
            return null;
        }
    }

    public static com.facebook.thrift.payload.Reader<ThriftOrder> asReader() {
        return ThriftOrder::read0;
    }

    public static ThriftOrder read0(TProtocol iprot) throws TException {
        return ThriftOrder.fromInteger(iprot.readI32());
    }

    public void write0(TProtocol oprot) throws TException {
        oprot.writeI32(getValue());
    }


}
