/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftTaskId", builder=ThriftTaskId.Builder.class)
public final class ThriftTaskId implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftTaskId(
        @com.facebook.swift.codec.ThriftField(value=1, name="stageExecutionId", requiredness=Requiredness.NONE) final com.facebook.presto.common.experimental.auto_gen.ThriftStageExecutionId stageExecutionId,
        @com.facebook.swift.codec.ThriftField(value=2, name="id", requiredness=Requiredness.NONE) final int id,
        @com.facebook.swift.codec.ThriftField(value=3, name="attemptNumber", requiredness=Requiredness.NONE) final int attemptNumber
    ) {
        this.stageExecutionId = stageExecutionId;
        this.id = id;
        this.attemptNumber = attemptNumber;
    }
    
    @ThriftConstructor
    protected ThriftTaskId() {
      this.stageExecutionId = null;
      this.id = 0;
      this.attemptNumber = 0;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftTaskId other) {
      return new Builder(other);
    }

    public static class Builder {
        private com.facebook.presto.common.experimental.auto_gen.ThriftStageExecutionId stageExecutionId = null;
        private int id = 0;
        private int attemptNumber = 0;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="stageExecutionId", requiredness=Requiredness.NONE)    public Builder setStageExecutionId(com.facebook.presto.common.experimental.auto_gen.ThriftStageExecutionId stageExecutionId) {
            this.stageExecutionId = stageExecutionId;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftStageExecutionId getStageExecutionId() { return stageExecutionId; }
    
            @com.facebook.swift.codec.ThriftField(value=2, name="id", requiredness=Requiredness.NONE)    public Builder setId(int id) {
            this.id = id;
            return this;
        }
    
        public int getId() { return id; }
    
            @com.facebook.swift.codec.ThriftField(value=3, name="attemptNumber", requiredness=Requiredness.NONE)    public Builder setAttemptNumber(int attemptNumber) {
            this.attemptNumber = attemptNumber;
            return this;
        }
    
        public int getAttemptNumber() { return attemptNumber; }
    
        public Builder() { }
        public Builder(ThriftTaskId other) {
            this.stageExecutionId = other.stageExecutionId;
            this.id = other.id;
            this.attemptNumber = other.attemptNumber;
        }
    
        @ThriftConstructor
        public ThriftTaskId build() {
            ThriftTaskId result = new ThriftTaskId (
                this.stageExecutionId,
                this.id,
                this.attemptNumber
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftTaskId");
    private final com.facebook.presto.common.experimental.auto_gen.ThriftStageExecutionId stageExecutionId;
    public static final int _STAGEEXECUTIONID = 1;
    private static final TField STAGE_EXECUTION_ID_FIELD_DESC = new TField("stageExecutionId", TType.STRUCT, (short)1);
        private final int id;
    public static final int _ID = 2;
    private static final TField ID_FIELD_DESC = new TField("id", TType.I32, (short)2);
        private final int attemptNumber;
    public static final int _ATTEMPTNUMBER = 3;
    private static final TField ATTEMPT_NUMBER_FIELD_DESC = new TField("attemptNumber", TType.I32, (short)3);
    static {
      NAMES_TO_IDS.put("stageExecutionId", 1);
      THRIFT_NAMES_TO_IDS.put("stageExecutionId", 1);
      FIELD_METADATA.put(1, STAGE_EXECUTION_ID_FIELD_DESC);
      NAMES_TO_IDS.put("id", 2);
      THRIFT_NAMES_TO_IDS.put("id", 2);
      FIELD_METADATA.put(2, ID_FIELD_DESC);
      NAMES_TO_IDS.put("attemptNumber", 3);
      THRIFT_NAMES_TO_IDS.put("attemptNumber", 3);
      FIELD_METADATA.put(3, ATTEMPT_NUMBER_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="stageExecutionId", requiredness=Requiredness.NONE)
    public com.facebook.presto.common.experimental.auto_gen.ThriftStageExecutionId getStageExecutionId() { return stageExecutionId; }

    
    
    @com.facebook.swift.codec.ThriftField(value=2, name="id", requiredness=Requiredness.NONE)
    public int getId() { return id; }

    
    
    @com.facebook.swift.codec.ThriftField(value=3, name="attemptNumber", requiredness=Requiredness.NONE)
    public int getAttemptNumber() { return attemptNumber; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("stageExecutionId", stageExecutionId);
        helper.add("id", id);
        helper.add("attemptNumber", attemptNumber);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftTaskId other = (ThriftTaskId)o;
    
        return
            Objects.equals(stageExecutionId, other.stageExecutionId) &&
            Objects.equals(id, other.id) &&
            Objects.equals(attemptNumber, other.attemptNumber) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            stageExecutionId,
            id,
            attemptNumber
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftTaskId> asReader() {
      return ThriftTaskId::read0;
    }
    
    public static ThriftTaskId read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftTaskId.NAMES_TO_IDS, ThriftTaskId.THRIFT_NAMES_TO_IDS, ThriftTaskId.FIELD_METADATA);
      ThriftTaskId.Builder builder = new ThriftTaskId.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _STAGEEXECUTIONID:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftStageExecutionId stageExecutionId = com.facebook.presto.common.experimental.auto_gen.ThriftStageExecutionId.read0(oprot);
            builder.setStageExecutionId(stageExecutionId);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _ID:
          if (__field.type == TType.I32) {
            int id = oprot.readI32();
            builder.setId(id);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _ATTEMPTNUMBER:
          if (__field.type == TType.I32) {
            int attemptNumber = oprot.readI32();
            builder.setAttemptNumber(attemptNumber);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (stageExecutionId != null) {
        oprot.writeFieldBegin(STAGE_EXECUTION_ID_FIELD_DESC);
        this.stageExecutionId.write0(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(this.id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ATTEMPT_NUMBER_FIELD_DESC);
      oprot.writeI32(this.attemptNumber);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftTaskIdLazy {
        private static final ThriftTaskId _DEFAULT = new ThriftTaskId.Builder().build();
    }
    
    public static ThriftTaskId defaultInstance() {
        return  _ThriftTaskIdLazy._DEFAULT;
    }
}
