/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.thrift.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftErrorCode", builder=ThriftErrorCode.Builder.class)
public final class ThriftErrorCode implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftErrorCode(
        @com.facebook.swift.codec.ThriftField(value=1, name="code", requiredness=Requiredness.NONE) final int code,
        @com.facebook.swift.codec.ThriftField(value=2, name="name", requiredness=Requiredness.NONE) final String name,
        @com.facebook.swift.codec.ThriftField(value=3, name="type", requiredness=Requiredness.NONE) final com.facebook.presto.common.experimental.auto_gen.ThriftErrorType type,
        @com.facebook.swift.codec.ThriftField(value=4, name="retriable", requiredness=Requiredness.NONE) final boolean retriable
    ) {
        this.code = code;
        this.name = name;
        this.type = type;
        this.retriable = retriable;
    }
    
    @ThriftConstructor
    protected ThriftErrorCode() {
      this.code = 0;
      this.name = null;
      this.type = com.facebook.presto.common.experimental.auto_gen.ThriftErrorType.fromInteger(0);
      this.retriable = false;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftErrorCode other) {
      return new Builder(other);
    }

    public static class Builder {
        private int code = 0;
        private String name = null;
        private com.facebook.presto.common.experimental.auto_gen.ThriftErrorType type = com.facebook.presto.common.experimental.auto_gen.ThriftErrorType.fromInteger(0);
        private boolean retriable = false;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="code", requiredness=Requiredness.NONE)    public Builder setCode(int code) {
            this.code = code;
            return this;
        }
    
        public int getCode() { return code; }
    
            @com.facebook.swift.codec.ThriftField(value=2, name="name", requiredness=Requiredness.NONE)    public Builder setName(String name) {
            this.name = name;
            return this;
        }
    
        public String getName() { return name; }
    
            @com.facebook.swift.codec.ThriftField(value=3, name="type", requiredness=Requiredness.NONE)    public Builder setType(com.facebook.presto.common.experimental.auto_gen.ThriftErrorType type) {
            this.type = type;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftErrorType getType() { return type; }
    
            @com.facebook.swift.codec.ThriftField(value=4, name="retriable", requiredness=Requiredness.NONE)    public Builder setRetriable(boolean retriable) {
            this.retriable = retriable;
            return this;
        }
    
        public boolean isRetriable() { return retriable; }
    
        public Builder() { }
        public Builder(ThriftErrorCode other) {
            this.code = other.code;
            this.name = other.name;
            this.type = other.type;
            this.retriable = other.retriable;
        }
    
        @ThriftConstructor
        public ThriftErrorCode build() {
            ThriftErrorCode result = new ThriftErrorCode (
                this.code,
                this.name,
                this.type,
                this.retriable
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftErrorCode");
    private final int code;
    public static final int _CODE = 1;
    private static final TField CODE_FIELD_DESC = new TField("code", TType.I32, (short)1);
        private final String name;
    public static final int _NAME = 2;
    private static final TField NAME_FIELD_DESC = new TField("name", TType.STRING, (short)2);
        private final com.facebook.presto.common.experimental.auto_gen.ThriftErrorType type;
    public static final int _TYPE = 3;
    private static final TField TYPE_FIELD_DESC = new TField("type", TType.I32, (short)3);
        private final boolean retriable;
    public static final int _RETRIABLE = 4;
    private static final TField RETRIABLE_FIELD_DESC = new TField("retriable", TType.BOOL, (short)4);
    static {
      NAMES_TO_IDS.put("code", 1);
      THRIFT_NAMES_TO_IDS.put("code", 1);
      FIELD_METADATA.put(1, CODE_FIELD_DESC);
      NAMES_TO_IDS.put("name", 2);
      THRIFT_NAMES_TO_IDS.put("name", 2);
      FIELD_METADATA.put(2, NAME_FIELD_DESC);
      NAMES_TO_IDS.put("type", 3);
      THRIFT_NAMES_TO_IDS.put("type", 3);
      FIELD_METADATA.put(3, TYPE_FIELD_DESC);
      NAMES_TO_IDS.put("retriable", 4);
      THRIFT_NAMES_TO_IDS.put("retriable", 4);
      FIELD_METADATA.put(4, RETRIABLE_FIELD_DESC);
    }
    
    
    @com.facebook.swift.codec.ThriftField(value=1, name="code", requiredness=Requiredness.NONE)
    public int getCode() { return code; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=2, name="name", requiredness=Requiredness.NONE)
    public String getName() { return name; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=3, name="type", requiredness=Requiredness.NONE)
    public com.facebook.presto.common.experimental.auto_gen.ThriftErrorType getType() { return type; }

    
    
    @com.facebook.swift.codec.ThriftField(value=4, name="retriable", requiredness=Requiredness.NONE)
    public boolean isRetriable() { return retriable; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("code", code);
        helper.add("name", name);
        helper.add("type", type);
        helper.add("retriable", retriable);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftErrorCode other = (ThriftErrorCode)o;
    
        return
            Objects.equals(code, other.code) &&
            Objects.equals(name, other.name) &&
            Objects.equals(type, other.type) &&
            Objects.equals(retriable, other.retriable) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            code,
            name,
            type,
            retriable
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftErrorCode> asReader() {
      return ThriftErrorCode::read0;
    }
    
    public static ThriftErrorCode read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftErrorCode.NAMES_TO_IDS, ThriftErrorCode.THRIFT_NAMES_TO_IDS, ThriftErrorCode.FIELD_METADATA);
      ThriftErrorCode.Builder builder = new ThriftErrorCode.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _CODE:
          if (__field.type == TType.I32) {
            int code = oprot.readI32();
            builder.setCode(code);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _NAME:
          if (__field.type == TType.STRING) {
            String name = oprot.readString();
            builder.setName(name);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _TYPE:
          if (__field.type == TType.I32) {
            com.facebook.presto.common.experimental.auto_gen.ThriftErrorType type = com.facebook.presto.common.experimental.auto_gen.ThriftErrorType.fromInteger(oprot.readI32());
            builder.setType(type);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _RETRIABLE:
          if (__field.type == TType.BOOL) {
            boolean retriable = oprot.readBool();
            builder.setRetriable(retriable);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CODE_FIELD_DESC);
      oprot.writeI32(this.code);
      oprot.writeFieldEnd();
      if (name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(this.name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TYPE_FIELD_DESC);
      oprot.writeI32(this.type == null ? 0 : com.facebook.thrift.util.EnumUtil.getValue(this.type));
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RETRIABLE_FIELD_DESC);
      oprot.writeBool(this.retriable);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftErrorCodeLazy {
        private static final ThriftErrorCode _DEFAULT = new ThriftErrorCode.Builder().build();
    }
    
    public static ThriftErrorCode defaultInstance() {
        return  _ThriftErrorCodeLazy._DEFAULT;
    }
}
