/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftStageExecutionId", builder=ThriftStageExecutionId.Builder.class)
public final class ThriftStageExecutionId implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftStageExecutionId(
        @com.facebook.swift.codec.ThriftField(value=1, name="stageId", requiredness=Requiredness.NONE) final com.facebook.presto.common.experimental.auto_gen.ThriftStageId stageId,
        @com.facebook.swift.codec.ThriftField(value=2, name="id", requiredness=Requiredness.NONE) final int id
    ) {
        this.stageId = stageId;
        this.id = id;
    }
    
    @ThriftConstructor
    protected ThriftStageExecutionId() {
      this.stageId = null;
      this.id = 0;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftStageExecutionId other) {
      return new Builder(other);
    }

    public static class Builder {
        private com.facebook.presto.common.experimental.auto_gen.ThriftStageId stageId = null;
        private int id = 0;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="stageId", requiredness=Requiredness.NONE)    public Builder setStageId(com.facebook.presto.common.experimental.auto_gen.ThriftStageId stageId) {
            this.stageId = stageId;
            return this;
        }
    
        public com.facebook.presto.common.experimental.auto_gen.ThriftStageId getStageId() { return stageId; }
    
            @com.facebook.swift.codec.ThriftField(value=2, name="id", requiredness=Requiredness.NONE)    public Builder setId(int id) {
            this.id = id;
            return this;
        }
    
        public int getId() { return id; }
    
        public Builder() { }
        public Builder(ThriftStageExecutionId other) {
            this.stageId = other.stageId;
            this.id = other.id;
        }
    
        @ThriftConstructor
        public ThriftStageExecutionId build() {
            ThriftStageExecutionId result = new ThriftStageExecutionId (
                this.stageId,
                this.id
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftStageExecutionId");
    private final com.facebook.presto.common.experimental.auto_gen.ThriftStageId stageId;
    public static final int _STAGEID = 1;
    private static final TField STAGE_ID_FIELD_DESC = new TField("stageId", TType.STRUCT, (short)1);
        private final int id;
    public static final int _ID = 2;
    private static final TField ID_FIELD_DESC = new TField("id", TType.I32, (short)2);
    static {
      NAMES_TO_IDS.put("stageId", 1);
      THRIFT_NAMES_TO_IDS.put("stageId", 1);
      FIELD_METADATA.put(1, STAGE_ID_FIELD_DESC);
      NAMES_TO_IDS.put("id", 2);
      THRIFT_NAMES_TO_IDS.put("id", 2);
      FIELD_METADATA.put(2, ID_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="stageId", requiredness=Requiredness.NONE)
    public com.facebook.presto.common.experimental.auto_gen.ThriftStageId getStageId() { return stageId; }

    
    
    @com.facebook.swift.codec.ThriftField(value=2, name="id", requiredness=Requiredness.NONE)
    public int getId() { return id; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("stageId", stageId);
        helper.add("id", id);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftStageExecutionId other = (ThriftStageExecutionId)o;
    
        return
            Objects.equals(stageId, other.stageId) &&
            Objects.equals(id, other.id) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            stageId,
            id
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftStageExecutionId> asReader() {
      return ThriftStageExecutionId::read0;
    }
    
    public static ThriftStageExecutionId read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftStageExecutionId.NAMES_TO_IDS, ThriftStageExecutionId.THRIFT_NAMES_TO_IDS, ThriftStageExecutionId.FIELD_METADATA);
      ThriftStageExecutionId.Builder builder = new ThriftStageExecutionId.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _STAGEID:
          if (__field.type == TType.STRUCT) {
            com.facebook.presto.common.experimental.auto_gen.ThriftStageId stageId = com.facebook.presto.common.experimental.auto_gen.ThriftStageId.read0(oprot);
            builder.setStageId(stageId);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _ID:
          if (__field.type == TType.I32) {
            int id = oprot.readI32();
            builder.setId(id);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (stageId != null) {
        oprot.writeFieldBegin(STAGE_ID_FIELD_DESC);
        this.stageId.write0(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(this.id);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftStageExecutionIdLazy {
        private static final ThriftStageExecutionId _DEFAULT = new ThriftStageExecutionId.Builder().build();
    }
    
    public static ThriftStageExecutionId defaultInstance() {
        return  _ThriftStageExecutionIdLazy._DEFAULT;
    }
}
