/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.facebook.presto.common.experimental.auto_gen;

import com.facebook.swift.codec.*;
import com.facebook.swift.codec.ThriftField.Requiredness;
import com.facebook.swift.codec.ThriftField.Recursiveness;
import com.google.common.collect.*;
import java.util.*;
import javax.annotation.Nullable;
import org.apache.fbthrift.*;
import org.apache.fbthrift.transport.*;
import org.apache.fbthrift.protocol.*;
import static com.google.common.base.MoreObjects.toStringHelper;
import static com.google.common.base.MoreObjects.ToStringHelper;

@SwiftGenerated
@com.facebook.swift.codec.ThriftStruct(value="ThriftColumnHandle", builder=ThriftColumnHandle.Builder.class)
public final class ThriftColumnHandle implements com.facebook.thrift.payload.ThriftSerializable {
    @ThriftConstructor
    public ThriftColumnHandle(
        @com.facebook.swift.codec.ThriftField(value=1, name="type", requiredness=Requiredness.NONE) final String type,
        @com.facebook.swift.codec.ThriftField(value=2, name="serializedHandle", requiredness=Requiredness.NONE) final byte[] serializedHandle
    ) {
        this.type = type;
        this.serializedHandle = serializedHandle;
    }
    
    @ThriftConstructor
    protected ThriftColumnHandle() {
      this.type = null;
      this.serializedHandle = null;
    }

    public static Builder builder() {
      return new Builder();
    }

    public static Builder builder(ThriftColumnHandle other) {
      return new Builder(other);
    }

    public static class Builder {
        private String type = null;
        private byte[] serializedHandle = null;
    
        @com.facebook.swift.codec.ThriftField(value=1, name="type", requiredness=Requiredness.NONE)    public Builder setType(String type) {
            this.type = type;
            return this;
        }
    
        public String getType() { return type; }
    
            @com.facebook.swift.codec.ThriftField(value=2, name="serializedHandle", requiredness=Requiredness.NONE)    public Builder setSerializedHandle(byte[] serializedHandle) {
            this.serializedHandle = serializedHandle;
            return this;
        }
    
        public byte[] getSerializedHandle() { return serializedHandle; }
    
        public Builder() { }
        public Builder(ThriftColumnHandle other) {
            this.type = other.type;
            this.serializedHandle = other.serializedHandle;
        }
    
        @ThriftConstructor
        public ThriftColumnHandle build() {
            ThriftColumnHandle result = new ThriftColumnHandle (
                this.type,
                this.serializedHandle
            );
            return result;
        }
    }
    
    public static final Map<String, Integer> NAMES_TO_IDS = new HashMap<>();
    public static final Map<String, Integer> THRIFT_NAMES_TO_IDS = new HashMap<>();
    public static final Map<Integer, TField> FIELD_METADATA = new HashMap<>();
    private static final TStruct STRUCT_DESC = new TStruct("ThriftColumnHandle");
    private final String type;
    public static final int _TYPE = 1;
    private static final TField TYPE_FIELD_DESC = new TField("type", TType.STRING, (short)1);
        private final byte[] serializedHandle;
    public static final int _SERIALIZEDHANDLE = 2;
    private static final TField SERIALIZED_HANDLE_FIELD_DESC = new TField("serializedHandle", TType.STRING, (short)2);
    static {
      NAMES_TO_IDS.put("type", 1);
      THRIFT_NAMES_TO_IDS.put("type", 1);
      FIELD_METADATA.put(1, TYPE_FIELD_DESC);
      NAMES_TO_IDS.put("serializedHandle", 2);
      THRIFT_NAMES_TO_IDS.put("serializedHandle", 2);
      FIELD_METADATA.put(2, SERIALIZED_HANDLE_FIELD_DESC);
    }
    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=1, name="type", requiredness=Requiredness.NONE)
    public String getType() { return type; }

    
    @Nullable
    @com.facebook.swift.codec.ThriftField(value=2, name="serializedHandle", requiredness=Requiredness.NONE)
    public byte[] getSerializedHandle() { return serializedHandle; }

    @java.lang.Override
    public String toString() {
        ToStringHelper helper = toStringHelper(this);
        helper.add("type", type);
        helper.add("serializedHandle", serializedHandle);
        return helper.toString();
    }

    @java.lang.Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
    
        ThriftColumnHandle other = (ThriftColumnHandle)o;
    
        return
            Objects.equals(type, other.type) &&
            Arrays.equals(serializedHandle, other.serializedHandle) &&
            true;
    }

    @java.lang.Override
    public int hashCode() {
        return Arrays.deepHashCode(new java.lang.Object[] {
            type,
            serializedHandle
        });
    }

    
    public static com.facebook.thrift.payload.Reader<ThriftColumnHandle> asReader() {
      return ThriftColumnHandle::read0;
    }
    
    public static ThriftColumnHandle read0(TProtocol oprot) throws TException {
      TField __field;
      oprot.readStructBegin(ThriftColumnHandle.NAMES_TO_IDS, ThriftColumnHandle.THRIFT_NAMES_TO_IDS, ThriftColumnHandle.FIELD_METADATA);
      ThriftColumnHandle.Builder builder = new ThriftColumnHandle.Builder();
      while (true) {
        __field = oprot.readFieldBegin();
        if (__field.type == TType.STOP) { break; }
        switch (__field.id) {
        case _TYPE:
          if (__field.type == TType.STRING) {
            String type = oprot.readString();
            builder.setType(type);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        case _SERIALIZEDHANDLE:
          if (__field.type == TType.STRING) {
            byte[] serializedHandle = oprot.readBinary().array();
            builder.setSerializedHandle(serializedHandle);
          } else {
            TProtocolUtil.skip(oprot, __field.type);
          }
          break;
        default:
          TProtocolUtil.skip(oprot, __field.type);
          break;
        }
        oprot.readFieldEnd();
      }
      oprot.readStructEnd();
      return builder.build();
    }

    public void write0(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);
      if (type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeString(this.type);
        oprot.writeFieldEnd();
      }
      if (serializedHandle != null) {
        oprot.writeFieldBegin(SERIALIZED_HANDLE_FIELD_DESC);
        oprot.writeBinary(java.nio.ByteBuffer.wrap(this.serializedHandle));
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    private static class _ThriftColumnHandleLazy {
        private static final ThriftColumnHandle _DEFAULT = new ThriftColumnHandle.Builder().build();
    }
    
    public static ThriftColumnHandle defaultInstance() {
        return  _ThriftColumnHandleLazy._DEFAULT;
    }
}
