# build.yaml
# Multi-architecture build matrix for Prestissimo
# Each combination spawns a separate native EC2 instance

matrix:
  arch: [arm64, amd64]
  cuda_version: ["12.8", "13.0"]
  ucx_version: ["1.19.1", "master"]
  instance_types:
    arm64: r8g.16xlarge
    amd64: m7a.16xlarge

