ARG PRESTO_VERSION

FROM ghcr.io/facebookincubator/velox-dev:circleci-avx as Builder

WORKDIR  /app
COPY . .
RUN cd presto-native-execution && \
    make velox-submodule && \
    source /opt/rh/gcc-toolset-9/enable && \
    ./scripts/setup-centos.sh && \
    EXTRA_CMAKE_FLAGS=" -DVELOX_ENABLE_INT64_BUILD_PARTITION_BOUND=ON -DPRESTO_ENABLE_TESTING=OFF" PRESTO_ENABLE_PARQUET=ON PRESTO_ENABLE_S3=ON MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=8 NUM_THREADS=8 TREAT_WARNINGS_AS_ERRORS=0 make release \
    || tail -n 500 _build/release/CMakeFiles/CMakeError.log

RUN cd presto-native-execution && \
    mkdir -p prestissimo && \
    cp _build/release/presto_cpp/main/presto_server prestissimo && \
    mkdir -p prestissimo/runtime-libraries && \
    ldd _build/release/presto_cpp/main/presto_server | awk 'NF == 4 { system("cp " $3 " prestissimo/runtime-libraries/") }' && \
    tar cvf prestissimo.tar entrypoint.sh velox.properties prestissimo

##

FROM quay.io/centos/centos:stream8

ENV PRESTO_HOME="/opt/presto-server"

RUN dnf update -y && dnf install -y epel-release
RUN dnf update -y && dnf --enablerepo=powertools install -y \
        awscli \
        gperf \
        iproute \
        lsof \
        procps \
        python3 \
        sysstat \
        tar \
        vim \
        wget \
        which \
        && \
    mkdir -p $PRESTO_HOME/etc/catalog && \
    mkdir -p /var/lib/presto/data

WORKDIR  /app
COPY --from=Builder /app/presto-native-execution/prestissimo.tar .
RUN tar xvf prestissimo.tar && \
    mkdir -p /opt/presto-server/etc && \
    mv prestissimo/presto_server /usr/local/bin/ && \
    mv velox.properties /opt/presto-server/etc/ && \
    mv entrypoint.sh /opt/ && \
    mv prestissimo/runtime-libraries/* /usr/local/lib/ && \
    touch /opt/presto-native-execution-${PRESTO_VERSION}

ENTRYPOINT ["/opt/entrypoint.sh"]

