ARG PRESTO_VERSION

FROM prestocpp/prestocpp-avx-centos:kpai-20221018 as Builder

WORKDIR  /app
COPY . .
RUN cd presto-native-execution && \
    make velox-submodule && \
    source /opt/rh/gcc-toolset-9/enable && \
    source velox/scripts/setup-helper-functions.sh && \
    (mkdir -p third_party && cd third_party && github_checkout aws/aws-sdk-cpp 1.9.96 --depth 1 --recurse-submodules --config advice.detachedHead=false && \
    cmake_install -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=OFF -DMINIMIZE_SIZE:BOOL=ON -DENABLE_TESTING:BOOL=OFF -DBUILD_ONLY:STRING="s3;identity-management") && \
    TREAT_WARNINGS_AS_ERRORS=0 PRESTO_ENABLE_PARQUET=ON PRESTO_ENABLE_S3=ON make release NUM_THREADS=8 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=8 && \
    mkdir -p prestissimo && \
    cp _build/release/presto_cpp/main/presto_server prestissimo && \
    tar cvf prestissimo.tar entrypoint.sh prestissimo

##

FROM prestocpp/prestocpp-avx-centos:kpai-20221018
ENV PRESTO_HOME="/opt/presto-server"

RUN dnf update -y && dnf install -y \
        awscli \
        gperf \
        iproute \
        lsof \
        procps \
        python3 \
        sysstat \
        tar \
        vim \
        wget \
        which \
        && \
    mkdir -p $PRESTO_HOME/etc/catalog && \
    mkdir -p /var/lib/presto/data

WORKDIR  /app
COPY --from=Builder /app/presto-native-execution/prestissimo.tar .
RUN tar xvf prestissimo.tar && \
    mv prestissimo/presto_server /usr/local/bin/ && \
    mv entrypoint.sh /opt/ && \
    touch /opt/presto-native-execution-${PRESTO_VERSION}

ENTRYPOINT ["/opt/entrypoint.sh"]
