#presto.server.uri=http://localhost:8081/
node.environment=testing
mcp.default-limit=10
presto.server.uri=https://localhost:8443
presto.server.user=presto
presto.server.password=password
presto.server.ssl.verification-disabled=true