FROM teradatalabs/centos6-java8-oracle
MAINTAINER Grzegorz Kokosiński <grzegorz.kokosinski@teradata.com>

COPY /presto-launcher-wrapper.sh /
COPY catalog /etc/catalog
COPY master /etc/master
COPY worker /etc/worker
