/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.facebook.presto.common.telemetry.tracing;

public enum TracingEnum
{
    ROOT("POST /v1/statement", ""),
    QUERY("query", ""),
    DISPATCH("dispatch", ""),
    ANALYZER("analyzer", ""),
    ANALYZE("analyze", ""),
    PLANNER("planner", ""),
    SCHEDULER("scheduler", ""),
    QUERY_START("query_start", ""),
    TASK("task", ""),
    SPLIT("split", ""),
    PIPELINE("pipeline", ""),
    LIST_SCHEMA_NAMES("listSchemaNames", ""),
    GET_TABLE_HANDLE_FOR_STATISTICS_COLLECTION("getTableHandleForStatisticsCollection", ""),
    GET_HANDLE_VERSION("getHandleVersion", ""),
    GET_SYSTEM_TABLE("getSystemTable", ""),
    GET_LAYOUT("getLayout", ""),
    GET_ALTERNATE_TABLE_HANDLE("getAlternativeTableHandle", ""),
    IS_LEGACY_GET_LAYOUT_SUPPORTED("isLegacyGetLayoutSupported", ""),
    GET_COMMON_PARTITIONING("getCommonPartitioning", ""),
    IS_REFINED_PARTITIONING_OVER("isRefinedPartitioningOver", ""),
    GET_PARTITIONING_HANDLE("getPartitioningHandleForExchange", ""),
    GET_PARTITIONING_HANDLE_CTE("getPartitioningHandleForCteMaterialization", ""),
    GET_INFO("getInfo", ""),
    CHECK_CAN_ADD_COLUMNS("checkCanAddColumns", ""),
    GET_TABLE_METADATA("getTableMetadata", ""),
    GET_TABLE_STATISTICS("getTableStatistics", ""),
    GET_COLUMN_HANDLES("getColumnHandles", ""),
    GET_COLUMN_METADATA("getColumnMetadata", ""),
    EXPLAIN_IO_CONSTRAINTS("toExplainIOConstraints", ""),
    LIST_TABLES("listTables", ""),
    LIST_TABLE_COLUMNS("listTableColumns", ""),
    CREATE_SCHEMA("createSchema", ""),
    DROP_SCHEMA("dropSchema", ""),
    RENAME_SCHEMA("renameSchema", ""),
    CREATE_TABLE("createTable", ""),
    CREATE_TEMPORARY_TABLE("createTemporaryTable", ""),
    CREATE_CONNECTOR_PARTITIONING_METADATA("createConnectorPartitioningMetadata", ""),
    RENAME_TABLE("renameTable", ""),
    RENAME_COLUMN("renameColumn", ""),
    ADD_COLUMN("addColumn", ""),
    DROP_COLUMN("dropColumn", ""),
    SET_COLUMN_TYPE("setColumnType", ""),
    DROP_TABLE("dropTable", ""),
    TRUNCATE_TABLE("truncateTable", ""),
    GET_INSERT_LAYOUT("getInsertLayout", ""),
    GET_PREFERRED_SHUFFLED_LAYOUT_FOR_INSERT("getPreferredShuffleLayoutForInsert", ""),
    GET_STATISTICS_COLLECTION_METADATA_FOR_WRITE("getStatisticsCollectionMetadataForWrite", ""),
    GET_STATISTICS_COLLECTION_METADATA("getStatisticsCollectionMetadata", ""),
    BEGIN_STATISTICS_COLLECTION("beginStatisticsCollection", ""),
    FINISH_STATISTICS_COLLECTION("finishStatisticsCollection", ""),
    GET_NEW_TABLE_LAYOUT("getNewTableLayout", ""),
    GET_PREFERRED_SHUFFLE_LAYOUT_FOR_NEW_TABLE("getPreferredShuffleLayoutForNewTable", ""),
    BEGIN_QUERY("beginQuery", ""),
    REGISTER_CATALOG_FOR_QUERY_ID("registerCatalogForQueryId", ""),
    CLEAN_UP_QUERY("cleanupQuery", ""),
    BEGIN_CREATE_TABLE("beginCreateTable", ""),
    FINISH_CREATE_TABLE("finishCreateTable", ""),
    BEGIN_INSERT("beginInsert", ""),
    FINISH_INSERT("finishInsert", ""),
    GET_DELETE_ROW_ID_COLUMN_HANDLE("getDeleteRowIdColumnHandle", ""),
    GET_UPDATE_ROW_ID_COLUMN_HANDLE("getUpdateRowIdColumnHandle", ""),
    SUPPORTS_METADATA_DELETE("supportsMetadataDelete", ""),
    METADATA_DELETE("metadataDelete", ""),
    BEGIN_DELETE("beginDelete", ""),
    FINISH_DELETE("finishDelete", ""),
    BEGIN_UPDATE("beginUpdate", ""),
    FINISH_UPDATE("finishUpdate", ""),
    GET_CATALOG_HANDLE("getCatalogHandle", ""),
    GET_CATALOG_NAMES("getCatalogNames", ""),
    LIST_VIEWS("listViews", ""),
    GET_VIEWS("getViews", ""),
    CREATE_VIEW("createView", ""),
    DROP_VIEW("dropView", ""),
    RENAME_VIEW("renameView", ""),
    CREATE_MATERIALIZED_VIEW("createMaterializedView", ""),
    DROP_MATERIALIZED_VIEW("dropMaterializedView", ""),
    GET_MATERIALIZED_VIEW_STATUS("getMaterializedViewStatus", ""),
    BEGIN_REFRESH_MATERIALIZED_VIEW("beginRefreshMaterializedView", ""),
    FINISH_REFRESH_MATERIALIZED_VIEW("finishRefreshMaterializedView", ""),
    GET_REFERENCED_MATERIALIZED_VIEWS("getReferencedMaterializedViews", ""),
    RESOLVE_INDEX("resolveIndex", ""),
    CREATE_ROLE("createRole", ""),
    DROP_ROLE("dropRole", ""),
    LIST_ROLES("listRoles", ""),
    LIST_ROLE_GRANTS("listRoleGrants", ""),
    GRANT_ROLES("grantRoles", ""),
    REVOKE_ROLES("revokeRoles", ""),
    LIST_APPLICABLE_ROLES("listApplicableRoles", ""),
    LIST_ENABLED_ROLES("listEnabledRoles", ""),
    GRANT_TABLE_PRIVILEGES("grantTablePrivileges", ""),
    REVOKE_TABLE_PRIVILEGES("revokeTablePrivileges", ""),
    LIST_TABLE_PRIVILEGES("listTablePrivileges", ""),
    COMMIT_PAGE_SINK_ASYNC("commitPageSinkAsync", ""),
    GET_METADATA_UPDATE_RESULTS("getMetadataUpdateResults", ""),
    GET_METADATA_RESOLVER("getMetadataResolver", ""),
    CATALOG_EXISTS("catalogExists", ""),
    SCHEMA_EXISTS("schemaExists", ""),
    TABLE_EXISTS("tableExists", ""),
    GET_TABLE_HANDLE("getTableHandle", ""),
    GET_COLUMNS("getColumns", ""),
    GET_VIEW("getView", ""),
    GET_MATERIALIZED_VIEW("getMaterializedView", ""),
    GET_CONNECTOR_CAPABILITIES("getConnectorCapabilities", ""),
    GET_TABLE_LAYOUT_FILTER_COVERAGE("getTableLayoutFilterCoverage", ""),
    DROP_CONSTRAINT("dropConstraint", ""),
    ADD_CONSTRAINT("addConstraint", ""),
    DESERIALIZE_VIEW("deserializeView", ""),
    GET_CATALOG_METADATA("getCatalogMetadata", ""),
    GET_CATALOG_METADATA_FOR_WRITE("getCatalogMetadataForWrite", ""),
    GET_METADATA("getMetadata", ""),
    GET_METADATA_FOR_WRITE("getMetadataForWrite", ""),
    CAN_RESOLVE_OPERATOR("canResolveOperator", ""),
    RESOLVE_TABLE_LAYOUT("resolveTableLayout", ""),
    GET_CATALOGS_BY_QUERY_ID("getCatalogsByQueryId", ""),
    ADD_SYSTEM_ACCESS_CONTROL_FACTORY("addSystemAccessControlFactory", ""),
    ADD_CATALOG_ACCESS_CONTROL("addCatalogAccessControl", ""),
    REMOVE_CATALOG_ACCESS_CONTROL("removeCatalogAccessControl", ""),
    LOAD_CATALOG_ACCESS_CONTROL("loadSystemAccessControl", ""),
    STAGE("stage", ""),
    LOAD_SYSTEM_ACCESS_CONTROL("loadSystemAccessControl", ""),
    SET_SYSTEM_ACCESS_CONTROL("setSystemAccessControl", ""),
    CHECK_CAN_SET_USER("checkCanSetUser", ""),
    SELECT_AUTHORIZED_IDENTITY("selectAuthorizedIdentity", ""),
    CHECK_QUERY_INTEGRITY("checkQueryIntegrity", ""),
    FILTER_CATALOGS("filterCatalogs", ""),
    CHECK_CAN_ACCESS_CATALOG("checkCanAccessCatalog", ""),
    CHECK_CAN_CREATE_SCHEMA("checkCanCreateSchema", ""),
    CHECK_CAN_DROP_SCHEMA("checkCanDropSchema", ""),
    CHECK_CAN_RENAME_SCHEMA("checkCanRenameSchema", ""),
    CHECK_CAN_SHOW_SCHEMAS("checkCanShowSchemas", ""),
    FILTER_SCHEMAS("filterSchemas", ""),
    CHECK_CAN_SHOW_CREATE_TABLE("checkCanShowCreateTable", ""),
    CHECK_CAN_CREATE_TABLE("checkCanCreateTable", ""),
    CHECK_CAN_DROP_TABLE("checkCanDropTable", ""),
    CHECK_CAN_RENAME_TABLE("checkCanRenameTable", ""),
    CHECK_CAN_SHOW_TABLES_METADATA("checkCanShowTablesMetadata", ""),
    FILTER_TABLES("filterTables", ""),
    CHECK_CAN_SHOW_COLUMNS_METADATA("checkCanShowColumnsMetadata", ""),
    FILTER_COLUMNS("filterColumns", ""),
    CHECK_CAN_ALTER_COLUMN("checkCanAlterColumn", ""),
    CHECK_CAN_DROP_COLUMN("checkCanDropColumn", ""),
    CHECK_CAN_INSERT_INTO_TABLE("checkCanInsertIntoTable", ""),
    CHECK_CAN_RENAME_COLUMN("checkCanRenameColumn", ""),
    CHECK_CAN_DELETE_FROM_TABLE("checkCanDeleteFromTable", ""),
    CHECK_CAN_TRUNCATE_TABLE("checkCanTruncateTable", ""),
    CHECK_CAN_UPDATE_TABLE_COLUMNS("checkCanUpdateTableColumns", ""),
    CHECK_CAN_CREATE_VIEW("checkCanCreateView", ""),
    CHECK_CAN_DROP_VIEW("checkCanDropView", ""),
    CHECK_CAN_RENAME_VIEW("checkCanRenameView", ""),
    CHECK_CAN_CREATE_VIEW_WITH_SELECT_FROM_COLUMNS("checkCanCreateViewWithSelectFromColumns", ""),
    CHECK_CAN_GRANT_TABLE_PRIVILEGE("checkCanGrantTablePrivilege", ""),
    CHECK_CAN_REVOKE_TABLE_PRIVILEGE("checkCanRevokeTablePrivilege", ""),
    CHECK_CAN_SET_SYSTEM_SESSION_PROPERTY("checkCanSetSystemSessionProperty", ""),
    CHECK_CAN_SET_CATALOG_SESSION_PROPERTY("checkCanSetCatalogSessionProperty", ""),
    CHECK_CAN_SELECT_FROM_COLUMNS("checkCanSelectFromColumns", ""),
    CHECK_CAN_CREATE_ROLE("checkCanCreateRole", ""),
    CHECK_CAN_DROP_ROLE("checkCanDropRole", ""),
    CHECK_CAN_GRANT_ROLES("checkCanGrantRoles", ""),
    CHECK_CAN_REVOKE_ROLES("checkCanRevokeRoles", ""),
    CHECK_CAN_SET_ROLE("checkCanSetRole", ""),
    CHECK_CAN_SHOW_ROLES("checkCanShowRoles", ""),
    CHECK_CAN_SHOW_CURRENT_ROLES("checkCanShowCurrentRoles", ""),
    CHECK_CAN_SHOW_ROLE_GRANTS("checkCanShowRoleGrants", ""),
    GET_ROW_FILTERS("getRowFilters", ""),
    GET_COLUMN_MASKS("getColumnMasks", ""),
    CHECK_CAN_DROP_CONSTRAINT("checkCanDropConstraint", ""),
    CHECK_CAN_ADD_CONSTRAINTS("checkCanAddConstraints", ""),
    GET_CONNECTOR_ACCESS_CONTROL("getConnectorAccessControl", "");

    private final String name;
    private final String description;

    TracingEnum(String name, String description)
    {
        this.name = name;
        this.description = description;
    }

    public String getName()
    {
        return this.name;
    }

    public String getDescription()
    {
        return this.description;
    }
}
