/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.facebook.presto.iceberg;

import com.facebook.presto.Session;
import com.facebook.presto.common.type.UnknownType;
import com.facebook.presto.testing.MaterializedResult;
import com.facebook.presto.testing.QueryRunner;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import static com.facebook.presto.common.type.IntegerType.INTEGER;
import static com.facebook.presto.iceberg.CatalogType.HIVE;
import static com.facebook.presto.testing.TestingSession.testSessionBuilder;
import static java.lang.String.format;
import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNull;

/**
 * Reads an Iceberg V3 table with an {@code unknown}-typed column produced by PySpark + the Iceberg
 * Spark runtime, proving Presto's ability to interoperate with Spark-written files.
 * <p>
 * The fixture at {@code src/test/resources/iceberg_v3/unknown_column/} was generated by PySpark
 * writing to a HadoopCatalog and contains 3 rows {@code (id=1..3, null_col=null)}.
 */
public class TestUnknownColumnRead
        extends IcebergImportedTableTestBase
{
    private static final String TABLE_NAME = "unknown_column";

    private String tablePath;
    private Session session;

    @Override
    protected QueryRunner createQueryRunner()
            throws Exception
    {
        session = testSessionBuilder()
                .setCatalog(CATALOGNAME)
                .setSchema(SCHEMANAME)
                .build();

        return IcebergQueryRunner.builder()
                .setCatalogType(HIVE)
                .setSchemaName(SCHEMANAME)
                .setCreateTpchTables(false)
                .build().getQueryRunner();
    }

    @BeforeMethod
    public void setup()
    {
        tablePath = setupAndRegisterTable(TABLE_NAME);
    }

    @AfterMethod(alwaysRun = true)
    public void teardown()
    {
        dropAndCleanupTable(TABLE_NAME, tablePath);
    }

    @Test
    public void testUnknownColumnRead()
    {
        // Schema: id INTEGER REQUIRED, null_col UNKNOWN OPTIONAL; 3 rows
        MaterializedResult result = computeActual(session,
                format("SELECT * FROM %s.%s.%s ORDER BY id", CATALOGNAME, SCHEMANAME, TABLE_NAME));

        assertEquals(result.getTypes().get(0), INTEGER);
        assertEquals(result.getTypes().get(1), UnknownType.UNKNOWN);
        assertEquals(result.getMaterializedRows().size(), 3);
        for (int i = 0; i < 3; i++) {
            assertEquals(result.getMaterializedRows().get(i).getField(0), i + 1);
            assertNull(result.getMaterializedRows().get(i).getField(1));
        }

        // Unknown columns are always null — IS NULL matches every row
        MaterializedResult isNullResult = computeActual(session,
                format("SELECT id FROM %s.%s.%s WHERE null_col IS NULL ORDER BY id", CATALOGNAME, SCHEMANAME, TABLE_NAME));
        assertEquals(isNullResult.getMaterializedRows().size(), 3);

        // IS NOT NULL matches no row
        MaterializedResult isNotNullResult = computeActual(session,
                format("SELECT count(*) FROM %s.%s.%s WHERE null_col IS NOT NULL", CATALOGNAME, SCHEMANAME, TABLE_NAME));
        assertEquals(isNotNullResult.getMaterializedRows().get(0).getField(0), 0L);
    }
}
