apiVersion: v1
kind: Pod
metadata:
    namespace: oss-agent
    labels:
        containers: maven
spec:
    serviceAccountName: oss-agent
    containers:
    - name: maven
      image: maven:3.8.6-openjdk-8-slim
      env:
      - name: MAVEN_OPTS
        value: "-Xmx6000m -Xms6000m"
      resources:
        requests:
          memory: "8Gi"
          cpu: "4000m"
        limits:
          memory: "8Gi"
          cpu: "4000m"
      tty: true
      command:
      - cat
