apiVersion: v1
kind: Pod
metadata:
    namespace: oss-agent
    labels:
        containers: dind
spec:
    nodeSelector:
      eks.amazonaws.com/nodegroup: eks-oss-presto-dynamic-managed-ng
    serviceAccountName: oss-agent
    containers:
    - name: dind
      image: docker:20.10.16-dind-alpine3.15
      securityContext:
        privileged: true
      tty: true
      resources:
        requests:
          memory: "29Gi"
          cpu: "7500m"
        limits:
          memory: "29Gi"
          cpu: "7500m"
