apiVersion: v1
kind: Pod
metadata:
    namespace: oss-agent
    labels:
        containers: dind
spec:
    serviceAccountName: oss-agent
    containers:
    - name: dind
      image: docker:20.10.16-dind-alpine3.15
      securityContext:
        privileged: true
      tty: true
      resources:
        requests:
          memory: "4Gi"
          cpu: "2000m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
