name: Maven OWASP Dependency Check Scan
description: Runs OWASP dependency check Maven scan with consistent settings
inputs:
  working-directory:
    description: Working directory for Maven command
    required: false
    default: .
  owasp-version:
    description: OWASP dependency check plugin version
    required: false
    default: 12.1.3
  data-directory:
    description: OWASP data directory path
    required: false
    default: /tmp/.owasp/dependency-check-data

runs:
  using: composite
  steps:
    - name: Run OWASP dependency check
      env:
        OWASP_VERSION: ${{ inputs.owasp-version }}
        OWASP_DATA_DIRECTORY: ${{ inputs.data-directory }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        mvn org.owasp:dependency-check-maven:$OWASP_VERSION:aggregate \
          -DskipTests \
          -Dformat=JSON \
          -DprettyPrint=true \
          -DfailOnError=false \
          -DossindexAnalyzerEnabled=true \
          -DnvdApiAnalyzerEnabled=false \
          -DnodeAnalyzerEnabled=false \
          -DassemblyAnalyzerEnabled=false \
          -DcentralAnalyzerEnabled=false \
          -DnuspecAnalyzerEnabled=false \
          -DnvdValidForHours=168 \
          -DdataDirectory=$OWASP_DATA_DIRECTORY
