/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated. Do not modify it manually. To re-generate it, run:
//
//  javac velox/type/tz/GenTimeZoneNames.java
//  java velox/type/tz/GenTimeZoneNames > velox/type/tz/TimeZoneNames.cpp
//
// Use the version of Java with which you're running Presto to generate
// compatible names. This version was generated using openjdk version
// "17.0.2"
// @generated

#include "velox/type/tz/TimeZoneNames.h"

#include <folly/Portability.h>

// This file just contains a single function that returns an, admittedly
// large, hard coded map.
FOLLY_CLANG_DISABLE_WARNING("-Wignored-optimization-argument");

namespace facebook::velox::tz {

const std::unordered_map<std::string, TimeZoneNames>& getTimeZoneNames() {
  static auto* timeZoneNames = new std::unordered_map<
      std::string,
      TimeZoneNames>([] {
    // Work around clang compiler bug causing multi-hour compilation
    // with -fsanitize=fuzzer
    // https://github.com/llvm/llvm-project/issues/75666
    return std::unordered_map<std::string, TimeZoneNames>{
        {"America/Los_Angeles",
         {"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT"}},
        {"America/Denver",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"America/Phoenix",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"America/Chicago",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/New_York",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Indianapolis",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"Pacific/Honolulu",
         {"Hawaii-Aleutian Standard Time",
          "HST",
          "Hawaii-Aleutian Daylight Time",
          "HDT"}},
        {"America/Anchorage",
         {"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT"}},
        {"America/Halifax",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Sitka",
         {"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT"}},
        {"America/St_Johns",
         {"Newfoundland Standard Time",
          "NST",
          "Newfoundland Daylight Time",
          "NDT"}},
        {"Europe/Paris",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"GMT", {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Asia/Jerusalem",
         {"Israel Standard Time", "IST", "Israel Daylight Time", "IDT"}},
        {"Asia/Tokyo",
         {"Japan Standard Time", "JST", "Japan Daylight Time", "JDT"}},
        {"Europe/Bucharest",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Asia/Shanghai",
         {"China Standard Time", "CST", "China Daylight Time", "CDT"}},
        {"UTC",
         {"Coordinated Universal Time",
          "UTC",
          "Coordinated Universal Time",
          "UTC"}},
        {"ACT",
         {"Australian Central Standard Time",
          "ACST",
          "Australian Central Daylight Time",
          "ACDT"}},
        {"AET",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"ART",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"AST",
         {"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT"}},
        {"BET",
         {"Brasilia Standard Time", "BRT", "Brasilia Summer Time", "BRST"}},
        {"BST",
         {"Bangladesh Standard Time", "BDT", "Bangladesh Summer Time", "BDST"}},
        {"CAT",
         {"Central Africa Time", "CAT", "Central African Summer Time", "CAST"}},
        {"CNT",
         {"Newfoundland Standard Time",
          "NST",
          "Newfoundland Daylight Time",
          "NDT"}},
        {"CST",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"CTT", {"China Standard Time", "CST", "China Daylight Time", "CDT"}},
        {"EAT",
         {"East Africa Time", "EAT", "Eastern African Summer Time", "EAST"}},
        {"ECT",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"JST", {"Japan Standard Time", "JST", "Japan Daylight Time", "JDT"}},
        {"MIT", {"Apia Standard Time", "WSST", "Apia Daylight Time", "WSDT"}},
        {"NET",
         {"Armenia Standard Time", "AMT", "Armenia Summer Time", "AMST"}},
        {"NST",
         {"New Zealand Standard Time",
          "NZST",
          "New Zealand Daylight Time",
          "NZDT"}},
        {"PLT",
         {"Pakistan Standard Time", "PKT", "Pakistan Summer Time", "PKST"}},
        {"PNT",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"PRT",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"PST",
         {"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT"}},
        {"SST",
         {"Solomon Islands Time", "SBT", "Solomon Is. Summer Time", "SBST"}},
        {"CST6CDT",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"EST5EDT",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"Etc/GMT",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Etc/UTC",
         {"Coordinated Universal Time",
          "UTC",
          "Coordinated Universal Time",
          "UTC"}},
        {"MST7MDT",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"PST8PDT",
         {"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT"}},
        {"Asia/Aden",
         {"Arabian Standard Time", "AST", "Arabian Daylight Time", "ADT"}},
        {"Asia/Baku",
         {"Azerbaijan Standard Time", "AZT", "Azerbaijan Summer Time", "AZST"}},
        {"Asia/Dili",
         {"East Timor Time", "TLT", "Timor-Leste Summer Time", "TLST"}},
        {"Asia/Gaza",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Asia/Hovd",
         {"Hovd Standard Time", "HOVT", "Hovd Summer Time", "HOVST"}},
        {"Asia/Omsk",
         {"Omsk Standard Time", "OMST", "Omsk Summer Time", "OMSST"}},
        {"Asia/Oral",
         {"West Kazakhstan Time", "ORAT", "Oral Summer Time", "ORAST"}},
        {"Asia/Amman",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Asia/Aqtau",
         {"West Kazakhstan Time", "AQTT", "Aqtau Summer Time", "AQTST"}},
        {"Asia/Chita",
         {"Yakutsk Standard Time", "YAKT", "Yakutsk Summer Time", "YAKST"}},
        {"Asia/Dhaka",
         {"Bangladesh Standard Time", "BDT", "Bangladesh Summer Time", "BDST"}},
        {"Asia/Dubai",
         {"Gulf Standard Time", "GST", "Gulf Daylight Time", "GDT"}},
        {"Asia/Kabul",
         {"Afghanistan Time", "AFT", "Afghanistan Summer Time", "AFST"}},
        {"Asia/Macau",
         {"China Standard Time", "CST", "China Daylight Time", "CDT"}},
        {"Asia/Qatar",
         {"Arabian Standard Time", "AST", "Arabian Daylight Time", "ADT"}},
        {"Asia/Seoul",
         {"Korean Standard Time", "KST", "Korean Daylight Time", "KDT"}},
        {"Africa/Juba",
         {"Central Africa Time", "CAT", "Central African Summer Time", "CAST"}},
        {"Africa/Lome",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Asia/Almaty",
         {"East Kazakhstan Time", "ALMT", "Alma-Ata Summer Time", "ALMST"}},
        {"Asia/Anadyr",
         {"Anadyr Standard Time", "ANAT", "Anadyr Summer Time", "ANAST"}},
        {"Asia/Aqtobe",
         {"West Kazakhstan Time", "AQTT", "Aqtobe Summer Time", "AQTST"}},
        {"Asia/Atyrau",
         {"West Kazakhstan Time",
          "GMT+05:00",
          "Atyrau Daylight Time",
          "GMT+05:00"}},
        {"Asia/Beirut",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Asia/Brunei",
         {"Brunei Darussalam Time", "BNT", "Brunei Summer Time", "BNST"}},
        {"Asia/Harbin",
         {"China Standard Time", "CST", "China Daylight Time", "CDT"}},
        {"Asia/Hebron",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Asia/Kuwait",
         {"Arabian Standard Time", "AST", "Arabian Daylight Time", "ADT"}},
        {"Asia/Manila",
         {"Philippine Standard Time", "PST", "Philippine Summer Time", "PDT"}},
        {"Asia/Muscat",
         {"Gulf Standard Time", "GST", "Gulf Daylight Time", "GDT"}},
        {"Asia/Riyadh",
         {"Arabian Standard Time", "AST", "Arabian Daylight Time", "ADT"}},
        {"Asia/Saigon",
         {"Indochina Time", "ICT", "Indochina Summer Time", "ICST"}},
        {"Asia/Taipei",
         {"Taipei Standard Time", "CST", "Taipei Daylight Time", "CDT"}},
        {"Asia/Tehran",
         {"Iran Standard Time", "IRST", "Iran Daylight Time", "IRDT"}},
        {"Europe/Kiev",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Europe/Oslo",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Riga",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Europe/Rome",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Indian/Mahe",
         {"Seychelles Time", "SCT", "Seychelles Summer Time", "SCST"}},
        {"Pacific/Yap", {"Chuuk Time", "CHUT", "Chuuk Summer Time", "CHUST"}},
        {"Africa/Accra",
         {"Greenwich Mean Time", "GMT", "Ghana Summer Time", "GHST"}},
        {"Africa/Cairo",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Africa/Ceuta",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Africa/Dakar",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Africa/Lagos",
         {"West Africa Standard Time",
          "WAT",
          "West Africa Summer Time",
          "WAST"}},
        {"Africa/Tunis",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"America/Adak",
         {"Hawaii-Aleutian Standard Time",
          "HAST",
          "Hawaii-Aleutian Daylight Time",
          "HADT"}},
        {"America/Lima",
         {"Peru Standard Time", "PET", "Peru Summer Time", "PEST"}},
        {"America/Nome",
         {"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT"}},
        {"Asia/Baghdad",
         {"Arabian Standard Time", "AST", "Arabian Daylight Time", "ADT"}},
        {"Asia/Bahrain",
         {"Arabian Standard Time", "AST", "Arabian Daylight Time", "ADT"}},
        {"Asia/Bangkok",
         {"Indochina Time", "ICT", "Indochina Summer Time", "ICST"}},
        {"Asia/Bishkek",
         {"Kyrgyzstan Time", "KGT", "Kirgizstan Summer Time", "KGST"}},
        {"Asia/Colombo",
         {"India Standard Time", "IST", "India Daylight Time", "IDT"}},
        {"Asia/Irkutsk",
         {"Irkutsk Standard Time", "IRKT", "Irkutsk Summer Time", "IRKST"}},
        {"Asia/Jakarta",
         {"Western Indonesia Time",
          "WIB",
          "West Indonesia Summer Time",
          "WIST"}},
        {"Asia/Karachi",
         {"Pakistan Standard Time", "PKT", "Pakistan Summer Time", "PKST"}},
        {"Asia/Kuching",
         {"Malaysia Time", "MYT", "Malaysia Summer Time", "MYST"}},
        {"Asia/Magadan",
         {"Magadan Standard Time", "MAGT", "Magadan Summer Time", "MAGST"}},
        {"Asia/Nicosia",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Asia/Rangoon",
         {"Myanmar Time", "MMT", "Myanmar Summer Time", "MMST"}},
        {"Asia/Tbilisi",
         {"Georgia Standard Time", "GET", "Georgia Summer Time", "GEST"}},
        {"Asia/Thimphu", {"Bhutan Time", "BTT", "Bhutan Summer Time", "BTST"}},
        {"Asia/Yakutsk",
         {"Yakutsk Standard Time", "YAKT", "Yakutsk Summer Time", "YAKST"}},
        {"Asia/Yerevan",
         {"Armenia Standard Time", "AMT", "Armenia Summer Time", "AMST"}},
        {"Europe/Malta",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Minsk",
         {"Moscow Standard Time", "MSK", "Moscow Summer Time", "MSD"}},
        {"Europe/Sofia",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Europe/Vaduz",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Indian/Cocos",
         {"Cocos Islands Time", "CCT", "Cocos Islands Summer Time", "CCST"}},
        {"Pacific/Apia",
         {"Apia Standard Time", "WSST", "Apia Daylight Time", "WSDT"}},
        {"Pacific/Fiji",
         {"Fiji Standard Time", "FJT", "Fiji Summer Time", "FJST"}},
        {"Pacific/Guam",
         {"Chamorro Standard Time", "ChST", "Chamorro Daylight Time", "ChDT"}},
        {"Pacific/Niue", {"Niue Time", "NUT", "Niue Summer Time", "NUST"}},
        {"Pacific/Truk", {"Chuuk Time", "CHUT", "Chuuk Summer Time", "CHUST"}},
        {"Pacific/Wake",
         {"Wake Island Time", "WAKT", "Wake Summer Time", "WAKST"}},
        {"SystemV/AST4",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"SystemV/CST6",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"SystemV/EST5",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"SystemV/MST7",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"SystemV/PST8",
         {"Pitcairn Time", "PST", "Pacific Daylight Time", "PDT"}},
        {"SystemV/YST9",
         {"Gambier Time", "AKST", "Alaska Daylight Time", "AKDT"}},
        {"Africa/Asmera",
         {"East Africa Time", "EAT", "Eastern African Summer Time", "EAST"}},
        {"Africa/Bamako",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Africa/Bangui",
         {"West Africa Standard Time",
          "WAT",
          "West Africa Summer Time",
          "WAST"}},
        {"Africa/Banjul",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Africa/Bissau",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Africa/Douala",
         {"West Africa Standard Time",
          "WAT",
          "West Africa Summer Time",
          "WAST"}},
        {"Africa/Harare",
         {"Central Africa Time", "CAT", "Central African Summer Time", "CAST"}},
        {"Africa/Kigali",
         {"Central Africa Time", "CAT", "Central African Summer Time", "CAST"}},
        {"Africa/Luanda",
         {"West Africa Standard Time",
          "WAT",
          "West Africa Summer Time",
          "WAST"}},
        {"Africa/Lusaka",
         {"Central Africa Time", "CAT", "Central African Summer Time", "CAST"}},
        {"Africa/Malabo",
         {"West Africa Standard Time",
          "WAT",
          "West Africa Summer Time",
          "WAST"}},
        {"Africa/Maputo",
         {"Central Africa Time", "CAT", "Central African Summer Time", "CAST"}},
        {"Africa/Maseru",
         {"South Africa Standard Time",
          "SAST",
          "South Africa Summer Time",
          "SAST"}},
        {"Africa/Niamey",
         {"West Africa Standard Time",
          "WAT",
          "West Africa Summer Time",
          "WAST"}},
        {"America/Aruba",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Bahia",
         {"Brasilia Standard Time", "BRT", "Brasilia Summer Time", "BRST"}},
        {"America/Belem",
         {"Brasilia Standard Time", "BRT", "Brasilia Summer Time", "BRST"}},
        {"America/Boise",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"America/Jujuy",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"America/Thule",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"Asia/Ashgabat",
         {"Turkmenistan Standard Time",
          "TMT",
          "Turkmenistan Summer Time",
          "TMST"}},
        {"Asia/Calcutta",
         {"India Standard Time", "IST", "India Daylight Time", "IDT"}},
        {"Asia/Damascus",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Asia/Dushanbe",
         {"Tajikistan Time", "TJT", "Tajikistan Summer Time", "TJST"}},
        {"Asia/Jayapura",
         {"Eastern Indonesia Time",
          "WIT",
          "East Indonesia Summer Time",
          "EIST"}},
        {"Asia/Katmandu", {"Nepal Time", "NPT", "Nepal Summer Time", "NPST"}},
        {"Asia/Khandyga",
         {"Yakutsk Standard Time", "YAKT", "Yakutsk Summer Time", "YAKST"}},
        {"Asia/Makassar",
         {"Central Indonesia Time",
          "WITA",
          "Central Indonesia Summer Time",
          "CIST"}},
        {"Asia/Qostanay",
         {"East Kazakhstan Time", "QOST", "Kostanay Summer Time", "QOSST"}},
        {"Asia/Sakhalin",
         {"Sakhalin Standard Time", "SAKT", "Sakhalin Summer Time", "SAKST"}},
        {"Asia/Tashkent",
         {"Uzbekistan Standard Time", "UZT", "Uzbekistan Summer Time", "UZST"}},
        {"Asia/Ust-Nera",
         {"Vladivostok Standard Time",
          "VLAT",
          "Vladivostok Summer Time",
          "VLAST"}},
        {"Europe/Athens",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Europe/Berlin",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Dublin",
         {"Greenwich Mean Time", "GMT", "Irish Standard Time", "IST"}},
        {"Europe/Jersey",
         {"Greenwich Mean Time", "GMT", "British Summer Time", "BST"}},
        {"Europe/Lisbon",
         {"Western European Standard Time",
          "WET",
          "Western European Summer Time",
          "WEST"}},
        {"Europe/London",
         {"Greenwich Mean Time", "GMT", "British Summer Time", "BST"}},
        {"Europe/Madrid",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Monaco",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Moscow",
         {"Moscow Standard Time", "MSK", "Moscow Summer Time", "MSD"}},
        {"Europe/Prague",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Samara",
         {"Samara Standard Time", "SAMT", "Samara Summer Time", "SAMST"}},
        {"Europe/Skopje",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Tirane",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Vienna",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Warsaw",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Zagreb",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Zurich",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Indian/Chagos",
         {"Indian Ocean Time",
          "IOT",
          "Indian Ocean Territory Summer Time",
          "IOST"}},
        {"Indian/Comoro",
         {"East Africa Time", "EAT", "Eastern African Summer Time", "EAST"}},
        {"Pacific/Efate",
         {"Vanuatu Standard Time", "VUT", "Vanuatu Summer Time", "VUST"}},
        {"Pacific/Nauru", {"Nauru Time", "NRT", "Nauru Summer Time", "NRST"}},
        {"Pacific/Palau", {"Palau Time", "PWT", "Palau Summer Time", "PWST"}},
        {"SystemV/HST10",
         {"Hawaii-Aleutian Standard Time",
          "HST",
          "Hawaii-Aleutian Daylight Time",
          "HDT"}},
        {"Africa/Abidjan",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Africa/Algiers",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Africa/Conakry",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Africa/Kampala",
         {"East Africa Time", "EAT", "Eastern African Summer Time", "EAST"}},
        {"Africa/Mbabane",
         {"South Africa Standard Time",
          "SAST",
          "South Africa Summer Time",
          "SAST"}},
        {"Africa/Nairobi",
         {"East Africa Time", "EAT", "Eastern African Summer Time", "EAST"}},
        {"Africa/Tripoli",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"America/Belize",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Bogota",
         {"Colombia Standard Time", "COT", "Colombia Summer Time", "COST"}},
        {"America/Cancun",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Cayman",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Cuiaba",
         {"Amazon Standard Time", "AMT", "Amazon Summer Time", "AMST"}},
        {"America/Dawson",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"America/Guyana",
         {"Guyana Time", "GYT", "Guyana Summer Time", "GYST"}},
        {"America/Havana",
         {"Cuba Standard Time", "CST", "Cuba Daylight Time", "CDT"}},
        {"America/Inuvik",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"America/Juneau",
         {"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT"}},
        {"America/La_Paz",
         {"Bolivia Time", "BOT", "Bolivia Summer Time", "BOST"}},
        {"America/Maceio",
         {"Brasilia Standard Time", "BRT", "Brasilia Summer Time", "BRST"}},
        {"America/Manaus",
         {"Amazon Standard Time", "AMT", "Amazon Summer Time", "AMST"}},
        {"America/Merida",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Nassau",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Panama",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Recife",
         {"Brasilia Standard Time", "BRT", "Brasilia Summer Time", "BRST"}},
        {"America/Regina",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"Asia/Chongqing",
         {"China Standard Time", "CST", "China Daylight Time", "CDT"}},
        {"Asia/Hong_Kong",
         {"Hong Kong Standard Time", "HKT", "Hong Kong Summer Time", "HKST"}},
        {"Asia/Kamchatka",
         {"Petropavlovsk-Kamchatski Standard Time",
          "PETT",
          "Petropavlovsk-Kamchatski Summer Time",
          "PETST"}},
        {"Asia/Pontianak",
         {"Western Indonesia Time",
          "WIB",
          "West Indonesia Summer Time",
          "WIST"}},
        {"Asia/Pyongyang",
         {"Korean Standard Time", "KST", "Korean Daylight Time", "KDT"}},
        {"Asia/Qyzylorda",
         {"West Kazakhstan Time", "QYZT", "Qyzylorda Summer Time", "QYZST"}},
        {"Asia/Samarkand",
         {"Uzbekistan Standard Time", "UZT", "Uzbekistan Summer Time", "UZST"}},
        {"Asia/Singapore",
         {"Singapore Standard Time", "SGT", "Singapore Summer Time", "SGST"}},
        {"Asia/Vientiane",
         {"Indochina Time", "ICT", "Indochina Summer Time", "ICST"}},
        {"Europe/Andorra",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Belfast",
         {"Greenwich Mean Time", "GMT", "British Summer Time", "BST"}},
        {"Europe/Tallinn",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Europe/Vatican",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Vilnius",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Indian/Mayotte",
         {"East Africa Time", "EAT", "Eastern African Summer Time", "EAST"}},
        {"Indian/Reunion",
         {"Réunion Time", "RET", "Reunion Summer Time", "REST"}},
        {"Pacific/Easter",
         {"Easter Island Standard Time",
          "EAST",
          "Easter Island Summer Time",
          "EASST"}},
        {"Pacific/Kosrae",
         {"Kosrae Time", "KOST", "Kosrae Summer Time", "KOSST"}},
        {"Pacific/Majuro",
         {"Marshall Islands Time",
          "MHT",
          "Marshall Islands Summer Time",
          "MHST"}},
        {"Pacific/Midway",
         {"Samoa Standard Time", "SST", "Samoa Daylight Time", "SDT"}},
        {"Pacific/Noumea",
         {"New Caledonia Standard Time",
          "NCT",
          "New Caledonia Summer Time",
          "NCST"}},
        {"Pacific/Ponape",
         {"Ponape Time", "PONT", "Pohnpei Summer Time", "PONST"}},
        {"Pacific/Saipan",
         {"Chamorro Standard Time", "ChST", "Chamorro Daylight Time", "ChDT"}},
        {"Pacific/Tahiti",
         {"Tahiti Time", "TAHT", "Tahiti Summer Time", "TAHST"}},
        {"Pacific/Tarawa",
         {"Gilbert Islands Time", "GILT", "Gilbert Is. Summer Time", "GILST"}},
        {"Pacific/Wallis",
         {"Wallis & Futuna Time",
          "WFT",
          "Wallis & Futuna Summer Time",
          "WFST"}},
        {"Africa/Blantyre",
         {"Central Africa Time", "CAT", "Central African Summer Time", "CAST"}},
        {"Africa/Djibouti",
         {"East Africa Time", "EAT", "Eastern African Summer Time", "EAST"}},
        {"Africa/Freetown",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Africa/Gaborone",
         {"Central Africa Time", "CAT", "Central African Summer Time", "CAST"}},
        {"Africa/Khartoum",
         {"Central Africa Time", "CAT", "Central African Summer Time", "CAST"}},
        {"Africa/Kinshasa",
         {"West Africa Standard Time",
          "WAT",
          "West Africa Summer Time",
          "WAST"}},
        {"Africa/Monrovia",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Africa/Ndjamena",
         {"West Africa Standard Time",
          "WAT",
          "West Africa Summer Time",
          "WAST"}},
        {"Africa/Sao_Tome",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Africa/Timbuktu",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Africa/Windhoek",
         {"Central Africa Time", "CAT", "Western African Time", "WAT"}},
        {"America/Antigua",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Caracas",
         {"Venezuela Time", "VET", "Venezuela Summer Time", "VEST"}},
        {"America/Cayenne",
         {"French Guiana Time", "GFT", "French Guiana Summer Time", "GFST"}},
        {"America/Cordoba",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"America/Creston",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"America/Curacao",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Detroit",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Godthab",
         {"West Greenland Standard Time",
          "WGT",
          "West Greenland Summer Time",
          "WGST"}},
        {"America/Grenada",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Iqaluit",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Jamaica",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Managua",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Marigot",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Mendoza",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"America/Moncton",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Nipigon",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Noronha",
         {"Fernando de Noronha Standard Time",
          "FNT",
          "Fernando de Noronha Summer Time",
          "FNST"}},
        {"America/Ojinaga",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"America/Tijuana",
         {"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT"}},
        {"America/Toronto",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Tortola",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Yakutat",
         {"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT"}},
        {"Asia/Choibalsan",
         {"Ulaanbaatar Standard Time",
          "CHOT",
          "Ulaanbaatar Summer Time",
          "CHOST"}},
        {"Asia/Phnom_Penh",
         {"Indochina Time", "ICT", "Indochina Summer Time", "ICST"}},
        {"Atlantic/Azores",
         {"Azores Standard Time", "AZOT", "Azores Summer Time", "AZOST"}},
        {"Atlantic/Canary",
         {"Western European Standard Time",
          "WET",
          "Western European Summer Time",
          "WEST"}},
        {"Atlantic/Faeroe",
         {"Western European Standard Time",
          "WET",
          "Western European Summer Time",
          "WEST"}},
        {"Australia/Eucla",
         {"Australian Central Western Standard Time",
          "ACWST",
          "Australian Central Western Daylight Time",
          "ACWDT"}},
        {"Australia/Perth",
         {"Australian Western Standard Time",
          "AWST",
          "Australian Western Daylight Time",
          "AWDT"}},
        {"Europe/Belgrade",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Brussels",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Budapest",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Busingen",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Chisinau",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Europe/Guernsey",
         {"Greenwich Mean Time", "GMT", "British Summer Time", "BST"}},
        {"Europe/Helsinki",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Europe/Sarajevo",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Uzhgorod",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Indian/Maldives",
         {"Maldives Time", "MVT", "Maldives Summer Time", "MVST"}},
        {"Pacific/Chatham",
         {"Chatham Standard Time", "CHAST", "Chatham Daylight Time", "CHADT"}},
        {"Pacific/Fakaofo",
         {"Tokelau Time", "TKT", "Tokelau Summer Time", "TKST"}},
        {"Pacific/Gambier",
         {"Gambier Time", "GAMT", "Gambier Summer Time", "GAMST"}},
        {"Pacific/Norfolk",
         {"Norfolk Island Standard Time",
          "NFT",
          "Norfolk Island Daylight Time",
          "NFST"}},
        {"SystemV/AST4ADT",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"SystemV/CST6CDT",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"SystemV/EST5EDT",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"SystemV/MST7MDT",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"SystemV/PST8PDT",
         {"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT"}},
        {"SystemV/YST9YDT",
         {"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT"}},
        {"Africa/Bujumbura",
         {"Central Africa Time", "CAT", "Central African Summer Time", "CAST"}},
        {"Africa/Mogadishu",
         {"East Africa Time", "EAT", "Eastern African Summer Time", "EAST"}},
        {"America/Anguilla",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Asuncion",
         {"Paraguay Standard Time", "PYT", "Paraguay Summer Time", "PYST"}},
        {"America/Barbados",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Dominica",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Edmonton",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"America/Eirunepe",
         {"Acre Standard Time", "ACT", "Acre Summer Time", "ACST"}},
        {"America/Mazatlan",
         {"Mexican Pacific Standard Time",
          "MST",
          "Mexican Pacific Daylight Time",
          "MDT"}},
        {"America/Miquelon",
         {"St. Pierre & Miquelon Standard Time",
          "PMST",
          "St. Pierre & Miquelon Daylight Time",
          "PMDT"}},
        {"America/Montreal",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Resolute",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Santarem",
         {"Brasilia Standard Time", "BRT", "Brasilia Summer Time", "BRST"}},
        {"America/Santiago",
         {"Chile Standard Time", "CLT", "Chile Summer Time", "CLST"}},
        {"America/Shiprock",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"America/St_Kitts",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/St_Lucia",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Winnipeg",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"Antarctica/Casey",
         {"Casey Time", "AWST", "Australian Western Daylight Time", "AWDT"}},
        {"Antarctica/Davis",
         {"Davis Time", "DAVT", "Davis Summer Time", "DAVST"}},
        {"Antarctica/Syowa",
         {"Syowa Time", "SYOT", "Syowa Summer Time", "SYOST"}},
        {"Antarctica/Troll",
         {"Greenwich Mean Time",
          "GMT",
          "Central European Summer Time",
          "CEST"}},
        {"Asia/Krasnoyarsk",
         {"Krasnoyarsk Standard Time",
          "KRAT",
          "Krasnoyarsk Summer Time",
          "KRAST"}},
        {"Asia/Novosibirsk",
         {"Novosibirsk Standard Time",
          "NOVT",
          "Novosibirsk Summer Time",
          "NOVST"}},
        {"Asia/Ulaanbaatar",
         {"Ulaanbaatar Standard Time",
          "ULAT",
          "Ulaanbaatar Summer Time",
          "ULAST"}},
        {"Asia/Vladivostok",
         {"Vladivostok Standard Time",
          "VLAT",
          "Vladivostok Summer Time",
          "VLAST"}},
        {"Atlantic/Bermuda",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"Atlantic/Madeira",
         {"Western European Standard Time",
          "WET",
          "Western European Summer Time",
          "WEST"}},
        {"Atlantic/Stanley",
         {"Falkland Islands Standard Time",
          "FKT",
          "Falkland Islands Summer Time",
          "FKST"}},
        {"Australia/Currie",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"Australia/Darwin",
         {"Australian Central Standard Time",
          "ACST",
          "Australian Central Daylight Time",
          "ACDT"}},
        {"Australia/Hobart",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"Australia/Sydney",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"Europe/Amsterdam",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Gibraltar",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Ljubljana",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Mariehamn",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Europe/Podgorica",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Stockholm",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Volgograd",
         {"Volgograd Standard Time", "MSK", "Volgograd Summer Time", "MSD"}},
        {"Indian/Christmas",
         {"Christmas Island Time",
          "CXT",
          "Christmas Island Summer Time",
          "CXST"}},
        {"Indian/Kerguelen",
         {"French Southern & Antarctic Time",
          "TFT",
          "French Southern & Antarctic Lands Summer Time",
          "TFST"}},
        {"Indian/Mauritius",
         {"Mauritius Standard Time", "MUT", "Mauritius Summer Time", "MUST"}},
        {"Pacific/Auckland",
         {"New Zealand Standard Time",
          "NZST",
          "New Zealand Daylight Time",
          "NZDT"}},
        {"Pacific/Funafuti",
         {"Tuvalu Time", "TVT", "Tuvalu Summer Time", "TVST"}},
        {"Pacific/Johnston",
         {"Hawaii-Aleutian Standard Time",
          "HAST",
          "Hawaii-Aleutian Daylight Time",
          "HADT"}},
        {"Pacific/Pitcairn",
         {"Pitcairn Time", "PST", "Pitcairn Daylight Time", "PDT"}},
        {"Africa/Libreville",
         {"West Africa Standard Time",
          "WAT",
          "West Africa Summer Time",
          "WAST"}},
        {"Africa/Lubumbashi",
         {"Central Africa Time", "CAT", "Central African Summer Time", "CAST"}},
        {"Africa/Nouakchott",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Africa/Porto-Novo",
         {"West Africa Standard Time",
          "WAT",
          "West Africa Summer Time",
          "WAST"}},
        {"America/Araguaina",
         {"Brasilia Standard Time", "BRT", "Brasilia Summer Time", "BRST"}},
        {"America/Boa_Vista",
         {"Amazon Standard Time", "AMT", "Amazon Summer Time", "AMST"}},
        {"America/Catamarca",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"America/Chihuahua",
         {"Mexican Pacific Standard Time",
          "MST",
          "Mexican Pacific Daylight Time",
          "MDT"}},
        {"America/Fortaleza",
         {"Brasilia Standard Time", "BRT", "Brasilia Summer Time", "BRST"}},
        {"America/Glace_Bay",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Goose_Bay",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Guatemala",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Guayaquil",
         {"Ecuador Time", "ECT", "Ecuador Summer Time", "ECST"}},
        {"America/Matamoros",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Menominee",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Monterrey",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Sao_Paulo",
         {"Brasilia Standard Time", "BRT", "Brasilia Summer Time", "BRST"}},
        {"America/St_Thomas",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Vancouver",
         {"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT"}},
        {"Antarctica/Mawson",
         {"Mawson Time", "MAWT", "Mawson Summer Time", "MAWST"}},
        {"Antarctica/Vostok",
         {"Vostok Time", "VOST", "Vostok Summer Time", "VOSST"}},
        {"Asia/Kuala_Lumpur",
         {"Malaysia Time", "MYT", "Malaysia Summer Time", "MYST"}},
        {"Asia/Novokuznetsk",
         {"Krasnoyarsk Standard Time",
          "KRAT",
          "Krasnoyarsk Summer Time",
          "KRAST"}},
        {"Europe/Bratislava",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Copenhagen",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Luxembourg",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/San_Marino",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Simferopol",
         {"Moscow Standard Time", "MSK", "Moscow Summer Time", "MSD"}},
        {"Europe/Zaporozhye",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Pacific/Enderbury",
         {"Phoenix Islands Time", "PHOT", "Phoenix Is. Summer Time", "PHOST"}},
        {"Pacific/Galapagos",
         {"Galapagos Time", "GALT", "Galapagos Summer Time", "GALST"}},
        {"Pacific/Kwajalein",
         {"Marshall Islands Time",
          "MHT",
          "Marshall Islands Summer Time",
          "MHST"}},
        {"Pacific/Marquesas",
         {"Marquesas Time", "MART", "Marquesas Summer Time", "MARST"}},
        {"Pacific/Pago_Pago",
         {"Samoa Standard Time", "SST", "Samoa Daylight Time", "SDT"}},
        {"Pacific/Rarotonga",
         {"Cook Islands Standard Time",
          "CKT",
          "Cook Islands Half Summer Time",
          "CKHST"}},
        {"Pacific/Tongatapu",
         {"Tonga Standard Time", "TOT", "Tonga Summer Time", "TOST"}},
        {"Africa/Addis_Ababa",
         {"East Africa Time", "EAT", "Eastern African Summer Time", "EAST"}},
        {"Africa/Brazzaville",
         {"West Africa Standard Time",
          "WAT",
          "West Africa Summer Time",
          "WAST"}},
        {"Africa/Ouagadougou",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"America/Costa_Rica",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Grand_Turk",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Guadeloupe",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Hermosillo",
         {"Mexican Pacific Standard Time",
          "MST",
          "Mexican Pacific Daylight Time",
          "MDT"}},
        {"America/Kralendijk",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Louisville",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Martinique",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Metlakatla",
         {"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT"}},
        {"America/Montevideo",
         {"Uruguay Standard Time", "UYT", "Uruguay Summer Time", "UYST"}},
        {"America/Montserrat",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Paramaribo",
         {"Suriname Time", "SRT", "Suriname Summer Time", "SRST"}},
        {"America/Rio_Branco",
         {"Acre Standard Time", "ACT", "Acre Summer Time", "ACST"}},
        {"America/St_Vincent",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Whitehorse",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"Antarctica/McMurdo",
         {"New Zealand Standard Time",
          "NZST",
          "New Zealand Daylight Time",
          "NZDT"}},
        {"Antarctica/Rothera",
         {"Rothera Time", "ROTT", "Rothera Summer Time", "ROTST"}},
        {"Asia/Yekaterinburg",
         {"Yekaterinburg Standard Time",
          "YEKT",
          "Yekaterinburg Summer Time",
          "YEKST"}},
        {"Atlantic/Jan_Mayen",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Atlantic/Reykjavik",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Atlantic/St_Helena",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Australia/Adelaide",
         {"Australian Central Standard Time",
          "ACST",
          "Australian Central Daylight Time",
          "ACDT"}},
        {"Australia/Brisbane",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"Australia/Lindeman",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"Europe/Isle_of_Man",
         {"Greenwich Mean Time", "GMT", "British Summer Time", "BST"}},
        {"Europe/Kaliningrad",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Pacific/Kiritimati",
         {"Line Islands Time", "LINT", "Line Is. Summer Time", "LINST"}},
        {"Africa/Johannesburg",
         {"South Africa Standard Time",
          "SAST",
          "South Africa Summer Time",
          "SAST"}},
        {"America/El_Salvador",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Fort_Nelson",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"America/Mexico_City",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Pangnirtung",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Porto_Velho",
         {"Amazon Standard Time", "AMT", "Amazon Summer Time", "AMST"}},
        {"America/Puerto_Rico",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Rainy_River",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Tegucigalpa",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Thunder_Bay",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Yellowknife",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"Arctic/Longyearbyen",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Atlantic/Cape_Verde",
         {"Cape Verde Standard Time", "CVT", "Cape Verde Summer Time", "CVST"}},
        {"Australia/Lord_Howe",
         {"Lord Howe Standard Time",
          "LHST",
          "Lord Howe Daylight Time",
          "LHDT"}},
        {"Australia/Melbourne",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"Indian/Antananarivo",
         {"East Africa Time", "EAT", "Eastern African Summer Time", "EAST"}},
        {"Pacific/Guadalcanal",
         {"Solomon Islands Time", "SBT", "Solomon Is. Summer Time", "SBST"}},
        {"Africa/Dar_es_Salaam",
         {"East Africa Time", "EAT", "Eastern African Summer Time", "EAST"}},
        {"America/Blanc-Sablon",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Buenos_Aires",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"America/Campo_Grande",
         {"Amazon Standard Time", "AMT", "Amazon Summer Time", "AMST"}},
        {"America/Danmarkshavn",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"America/Dawson_Creek",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"America/Indiana/Knox",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Rankin_Inlet",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Santa_Isabel",
         {"Northwest Mexico Standard Time",
          "PST",
          "Northwest Mexico Daylight Time",
          "PDT"}},
        {"America/Scoresbysund",
         {"East Greenland Standard Time",
          "EGT",
          "East Greenland Summer Time",
          "EGST"}},
        {"Antarctica/Macquarie",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"Pacific/Port_Moresby",
         {"Papua New Guinea Time",
          "PGT",
          "Papua New Guinea Summer Time",
          "PGST"}},
        {"America/Cambridge_Bay",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"America/Coral_Harbour",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Indiana/Vevay",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Lower_Princes",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Port_of_Spain",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Santo_Domingo",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/St_Barthelemy",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"America/Swift_Current",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"Antarctica/South_Pole",
         {"New Zealand Standard Time",
          "NZST",
          "New Zealand Daylight Time",
          "NZDT"}},
        {"Australia/Broken_Hill",
         {"Australian Central Standard Time",
          "ACST",
          "Australian Central Daylight Time",
          "ACDT"}},
        {"America/Bahia_Banderas",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Port-au-Prince",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"Atlantic/South_Georgia",
         {"South Georgia Time", "GST", "South Georgia Daylight Time", "GDT"}},
        {"America/Argentina/Salta",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"America/Indiana/Marengo",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Indiana/Winamac",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Argentina/Tucuman",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"America/Argentina/Ushuaia",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"America/Indiana/Tell_City",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Indiana/Vincennes",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"Antarctica/DumontDUrville",
         {"Dumont-d’Urville Time",
          "DDUT",
          "Dumont-d'Urville Summer Time",
          "DDUST"}},
        {"America/Argentina/La_Rioja",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"America/Argentina/San_Juan",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"America/Argentina/San_Luis",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"America/Indiana/Petersburg",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/Kentucky/Monticello",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"America/North_Dakota/Beulah",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/North_Dakota/Center",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"America/Argentina/Rio_Gallegos",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"America/North_Dakota/New_Salem",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"Asia/Chungking",
         {"China Standard Time", "CST", "China Daylight Time", "CDT"}},
        {"Asia/Kashgar",
         {"Xinjiang Standard Time", "XJT", "Xinjiang Daylight Time", "XJDT"}},
        {"Chile/Continental",
         {"Chile Standard Time", "CLT", "Chile Summer Time", "CLST"}},
        {"CET",
         {"Central European Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Europe/Istanbul",
         {"Turkey Time", "TRT", "Turkey Summer Time", "TRST"}},
        {"America/Argentina/Catamarca",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"Canada/Yukon",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"Canada/Atlantic",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"Australia/Tasmania",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"Libya",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"America/Argentina/Cordoba",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"IST", {"India Standard Time", "IST", "India Daylight Time", "IDT"}},
        {"US/Alaska",
         {"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT"}},
        {"Cuba", {"Cuba Standard Time", "CST", "Cuba Daylight Time", "CDT"}},
        {"Israel",
         {"Israel Standard Time", "IST", "Israel Daylight Time", "IDT"}},
        {"US/Arizona",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"Brazil/East",
         {"Brasilia Standard Time", "BRT", "Brasilia Summer Time", "BRST"}},
        {"Asia/Macao",
         {"China Standard Time", "CST", "China Daylight Time", "CDT"}},
        {"Asia/Tomsk",
         {"Tomsk Standard Time",
          "GMT+07:00",
          "Tomsk Daylight Time",
          "GMT+07:00"}},
        {"America/Argentina/Mendoza",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"Mexico/BajaSur",
         {"Mexican Pacific Standard Time",
          "MST",
          "Mexican Pacific Daylight Time",
          "MDT"}},
        {"HST", {"Hawaii Standard Time", "HST", "Hawaii Daylight Time", "HDT"}},
        {"Australia/ACT",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"GB-Eire",
         {"Greenwich Mean Time", "GMT", "British Summer Time", "BST"}},
        {"Asia/Dacca",
         {"Bangladesh Standard Time", "BDT", "Bangladesh Summer Time", "BDST"}},
        {"Pacific/Samoa",
         {"Samoa Standard Time", "SST", "Samoa Daylight Time", "SDT"}},
        {"America/Fort_Wayne",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"Europe/Saratov",
         {"Saratov Standard Time",
          "GMT+04:00",
          "Saratov Standard Time",
          "GMT+04:00"}},
        {"GB", {"Greenwich Mean Time", "GMT", "British Summer Time", "BST"}},
        {"Mexico/General",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"Asia/Istanbul", {"Turkey Time", "TRT", "Turkey Summer Time", "TRST"}},
        {"NZ-CHAT",
         {"Chatham Standard Time", "CHAST", "Chatham Daylight Time", "CHADT"}},
        {"America/Porto_Acre",
         {"Acre Standard Time", "ACT", "Acre Summer Time", "ACST"}},
        {"AGT", {"Argentine Time", "ART", "Argentine Summer Time", "ARST"}},
        {"US/Michigan",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"Europe/Tiraspol",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Portugal",
         {"Western European Standard Time",
          "WET",
          "Western European Summer Time",
          "WEST"}},
        {"America/Argentina/Jujuy",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"Universal",
         {"Coordinated Universal Time",
          "UTC",
          "Coordinated Universal Time",
          "UTC"}},
        {"Asia/Tel_Aviv",
         {"Israel Standard Time", "IST", "Israel Daylight Time", "IDT"}},
        {"Pacific/Bougainville",
         {"Bougainville Standard Time",
          "BST",
          "Bougainville Daylight Time",
          "BST"}},
        {"US/Central",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"Australia/North",
         {"Australian Central Standard Time",
          "ACST",
          "Australian Central Daylight Time",
          "ACDT"}},
        {"VST", {"Indochina Time", "ICT", "Indochina Summer Time", "ICST"}},
        {"Australia/Yancowinna",
         {"Australian Central Standard Time",
          "ACST",
          "Australian Central Daylight Time",
          "ACDT"}},
        {"Australia/Victoria",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"Asia/Barnaul",
         {"Barnaul Standard Time",
          "GMT+07:00",
          "Barnaul Daylight Time",
          "GMT+07:00"}},
        {"EST",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"Canada/Pacific",
         {"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT"}},
        {"Pacific/Chuuk", {"Chuuk Time", "CHUT", "Chuuk Summer Time", "CHUST"}},
        {"Etc/Universal",
         {"Coordinated Universal Time",
          "UTC",
          "Coordinated Universal Time",
          "UTC"}},
        {"Canada/Newfoundland",
         {"Newfoundland Standard Time",
          "NST",
          "Newfoundland Daylight Time",
          "NDT"}},
        {"America/Kentucky/Louisville",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"Asia/Ho_Chi_Minh",
         {"Indochina Time", "ICT", "Indochina Summer Time", "ICST"}},
        {"Africa/Asmara",
         {"East Africa Time", "EAT", "Eastern African Summer Time", "EAST"}},
        {"ROK", {"Korean Standard Time", "KST", "Korean Daylight Time", "KDT"}},
        {"Australia/Queensland",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"Asia/Kolkata",
         {"India Standard Time", "IST", "India Daylight Time", "IDT"}},
        {"Australia/Canberra",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"MET",
         {"Middle Europe Time", "MET", "Middle Europe Summer Time", "MEST"}},
        {"Kwajalein",
         {"Marshall Islands Time",
          "MHT",
          "Marshall Islands Summer Time",
          "MHST"}},
        {"Asia/Ulan_Bator",
         {"Ulaanbaatar Standard Time",
          "ULAT",
          "Ulaanbaatar Summer Time",
          "ULAST"}},
        {"NZ",
         {"New Zealand Standard Time",
          "NZST",
          "New Zealand Daylight Time",
          "NZDT"}},
        {"Eire", {"Greenwich Mean Time", "GMT", "Irish Standard Time", "IST"}},
        {"Atlantic/Faroe",
         {"Western European Standard Time",
          "WET",
          "Western European Summer Time",
          "WEST"}},
        {"Mexico/BajaNorte",
         {"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT"}},
        {"Etc/UCT",
         {"Coordinated Universal Time",
          "UTC",
          "Coordinated Universal Time",
          "UTC"}},
        {"America/Atka",
         {"Hawaii-Aleutian Standard Time",
          "HAST",
          "Hawaii-Aleutian Daylight Time",
          "HADT"}},
        {"America/Atikokan",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"Australia/NSW",
         {"Australian Eastern Standard Time",
          "AEST",
          "Australian Eastern Daylight Time",
          "AEDT"}},
        {"US/Hawaii",
         {"Hawaii-Aleutian Standard Time",
          "HST",
          "Hawaii-Aleutian Daylight Time",
          "HDT"}},
        {"Zulu",
         {"Coordinated Universal Time",
          "UTC",
          "Coordinated Universal Time",
          "UTC"}},
        {"Africa/El_Aaiun",
         {"Western European Time",
          "WET",
          "Western European Summer Time",
          "WEST"}},
        {"Brazil/West",
         {"Amazon Standard Time", "AMT", "Amazon Summer Time", "AMST"}},
        {"Chile/EasterIsland",
         {"Easter Island Standard Time",
          "EAST",
          "Easter Island Summer Time",
          "EASST"}},
        {"America/Indiana/Indianapolis",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"US/Mountain",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"Poland",
         {"Central European Standard Time",
          "CET",
          "Central European Summer Time",
          "CEST"}},
        {"Antarctica/Palmer",
         {"Chile Time", "CLT", "Chile Summer Time", "CLST"}},
        {"Asia/Yangon", {"Myanmar Time", "MMT", "Myanmar Summer Time", "MMST"}},
        {"Brazil/DeNoronha",
         {"Fernando de Noronha Standard Time",
          "FNT",
          "Fernando de Noronha Summer Time",
          "FNST"}},
        {"Asia/Ashkhabad",
         {"Turkmenistan Standard Time",
          "TMT",
          "Turkmenistan Summer Time",
          "TMST"}},
        {"Etc/Zulu",
         {"Coordinated Universal Time",
          "UTC",
          "Coordinated Universal Time",
          "UTC"}},
        {"America/Punta_Arenas",
         {"Punta Arenas Standard Time",
          "GMT-03:00",
          "Punta Arenas Standard Time",
          "GMT-03:00"}},
        {"US/Samoa",
         {"Samoa Standard Time", "SST", "Samoa Daylight Time", "SDT"}},
        {"PRC", {"China Standard Time", "CST", "China Daylight Time", "CDT"}},
        {"Iceland",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Pacific/Pohnpei",
         {"Ponape Time", "PONT", "Pohnpei Summer Time", "PONST"}},
        {"Asia/Ujung_Pandang",
         {"Central Indonesia Time",
          "WITA",
          "Central Indonesia Summer Time",
          "CIST"}},
        {"America/Knox_IN",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"Europe/Kirov",
         {"Kirov Standard Time",
          "GMT+03:00",
          "Kirov Daylight Time",
          "GMT+03:00"}},
        {"Pacific/Kanton",
         {"Kanton Standard Time",
          "GMT+13:00",
          "Kanton Daylight Time",
          "GMT+13:00"}},
        {"Greenwich",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"Australia/South",
         {"Australian Central Standard Time",
          "ACST",
          "Australian Central Daylight Time",
          "ACDT"}},
        {"Canada/Central",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"IET",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"US/Eastern",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"Africa/Casablanca",
         {"Western European Time",
          "WET",
          "Western European Summer Time",
          "WEST"}},
        {"Canada/Eastern",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"Singapore",
         {"Singapore Standard Time", "SGT", "Singapore Summer Time", "SGST"}},
        {"Brazil/Acre",
         {"Acre Standard Time", "ACT", "Acre Summer Time", "ACST"}},
        {"US/East-Indiana",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"Asia/Kathmandu", {"Nepal Time", "NPT", "Nepal Summer Time", "NPST"}},
        {"Australia/LHI",
         {"Lord Howe Standard Time",
          "LHST",
          "Lord Howe Daylight Time",
          "LHDT"}},
        {"Canada/Mountain",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"Australia/West",
         {"Australian Western Standard Time",
          "AWST",
          "Australian Western Daylight Time",
          "AWDT"}},
        {"US/Indiana-Starke",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"Asia/Urumqi",
         {"Xinjiang Standard Time", "XJT", "Xinjiang Daylight Time", "XJDT"}},
        {"US/Aleutian",
         {"Hawaii-Aleutian Standard Time",
          "HAST",
          "Hawaii-Aleutian Daylight Time",
          "HADT"}},
        {"Iran", {"Iran Standard Time", "IRST", "Iran Daylight Time", "IRDT"}},
        {"Asia/Thimbu", {"Bhutan Time", "BTT", "Bhutan Summer Time", "BTST"}},
        {"Navajo",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"Turkey", {"Turkey Time", "TRT", "Turkey Summer Time", "TRST"}},
        {"Jamaica",
         {"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT"}},
        {"WET",
         {"Western European Time",
          "WET",
          "Western European Summer Time",
          "WEST"}},
        {"Europe/Astrakhan",
         {"Astrakhan Standard Time",
          "GMT+04:00",
          "Astrakhan Standard Time",
          "GMT+04:00"}},
        {"Etc/Greenwich",
         {"Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT"}},
        {"America/Ensenada",
         {"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT"}},
        {"America/Virgin",
         {"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT"}},
        {"MST",
         {"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT"}},
        {"Hongkong",
         {"Hong Kong Standard Time", "HKT", "Hong Kong Summer Time", "HKST"}},
        {"UCT",
         {"Coordinated Universal Time",
          "UTC",
          "Coordinated Universal Time",
          "UTC"}},
        {"America/Argentina/ComodRivadavia",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"Asia/Famagusta",
         {"Eastern European Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Japan", {"Japan Standard Time", "JST", "Japan Daylight Time", "JDT"}},
        {"America/Nuuk",
         {"West Greenland Standard Time",
          "WGT",
          "West Greenland Summer Time",
          "WGST"}},
        {"Europe/Ulyanovsk",
         {"Ulyanovsk Standard Time",
          "GMT+04:00",
          "Ulyanovsk Standard Time",
          "GMT+04:00"}},
        {"W-SU", {"Moscow Standard Time", "MSK", "Moscow Summer Time", "MSD"}},
        {"EET",
         {"Eastern European Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"America/Rosario",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"Canada/Saskatchewan",
         {"Central Standard Time", "CST", "Central Daylight Time", "CDT"}},
        {"Egypt",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"Asia/Srednekolymsk",
         {"Srednekolymsk Time",
          "SRET",
          "Srednekolymsk Daylight Time",
          "SREDT"}},
        {"America/Argentina/Buenos_Aires",
         {"Argentina Standard Time", "ART", "Argentina Summer Time", "ARST"}},
        {"Europe/Nicosia",
         {"Eastern European Standard Time",
          "EET",
          "Eastern European Summer Time",
          "EEST"}},
        {"US/Pacific",
         {"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT"}},
    };
  }());
  return *timeZoneNames;
}

} // namespace facebook::velox::tz
