name: cleanup

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@2e3c1893986568a2197c41957b9c809cbcf1a61e
        with:
          token: ${{ github.token }}
          workflow: hive-tests.yml
      - uses: n1hility/cancel-previous-runs@2e3c1893986568a2197c41957b9c809cbcf1a61e
        with:
          token: ${{ github.token }}
          workflow: kudu.yml
      - uses: n1hility/cancel-previous-runs@2e3c1893986568a2197c41957b9c809cbcf1a61e
        with:
          token: ${{ github.token }}
          workflow: maven-checks.yml
      - uses: n1hility/cancel-previous-runs@2e3c1893986568a2197c41957b9c809cbcf1a61e
        with:
          token: ${{ github.token }}
          workflow: product-tests-basic-environment.yml
      - uses: n1hility/cancel-previous-runs@2e3c1893986568a2197c41957b9c809cbcf1a61e
        with:
          token: ${{ github.token }}
          workflow: product-tests-specific-environment.yml
      - uses: n1hility/cancel-previous-runs@2e3c1893986568a2197c41957b9c809cbcf1a61e
        with:
          token: ${{ github.token }}
          workflow: spark-integration.yml
      - uses: n1hility/cancel-previous-runs@2e3c1893986568a2197c41957b9c809cbcf1a61e
        with:
          token: ${{ github.token }}
          workflow: tests.yml
      - uses: n1hility/cancel-previous-runs@2e3c1893986568a2197c41957b9c809cbcf1a61e
        with:
          token: ${{ github.token }}
          workflow: web-ui-checks.yml
