name: hive tests

on:
  pull_request:
    paths-ignore:
      - presto-docs/**

env:
  # An envar that signals to tests we are executing in the CI environment
  CONTINUOUS_INTEGRATION: true
  MAVEN_OPTS: -Xmx1024M -XX:+ExitOnOutOfMemoryError
  MAVEN_INSTALL_OPTS: -Xmx2G -XX:+ExitOnOutOfMemoryError
  MAVEN_FAST_INSTALL: -B -V --quiet -T 1C -DskipTests -Dair.check.skip-all --no-transfer-progress -Dmaven.javadoc.skip=true
  MAVEN_TEST: -B -Dair.check.skip-all -Dmaven.javadoc.skip=true -DLogTestDurationListener.enabled=true --no-transfer-progress --fail-at-end
  RETRY: .github/bin/retry

jobs:
  hive-tests:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        java: ['17']
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: ${{ github.workflow }}-hive-tests-${{ github.event.pull_request.number }}-${{ matrix.java }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          persist-credentials: false
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Download nodejs to maven cache
        run: .github/bin/download_nodejs
      - name: Install Hive Module
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          ./mvnw install ${MAVEN_FAST_INSTALL} -am -pl :presto-hive-hadoop2
      - name: Run Hive Tests
        run: presto-hive-hadoop2/bin/run_hive_tests.sh
      - name: Run Hive S3 Tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HIVE_AWS_ACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HIVE_AWS_SECRETKEY }}
          S3_BUCKET: presto-ci-test
          S3_BUCKET_ENDPOINT: s3.us-east-2.amazonaws.com
        run: |
          if [ "${AWS_ACCESS_KEY_ID}" != "" ]; then
              presto-hive-hadoop2/bin/run_hive_s3_tests.sh
          fi
      - name: Run Hive Glue Tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HIVE_AWS_ACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HIVE_AWS_SECRETKEY }}
        run: |
          if [ "${HIVE_AWS_ACCESS_KEY_ID}" != "" ]; then
              ./mvnw test ${MAVEN_TEST} -pl :presto-hive -P test-hive-glue
          fi

  hive-dockerized-tests:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        java: ['17']
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-hive-dockerized-tests-${{ github.event.pull_request.number }}-${{ matrix.java }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          persist-credentials: false
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Download nodejs to maven cache
        run: .github/bin/download_nodejs
      - name: Install Hive Module
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          ./mvnw install ${MAVEN_FAST_INSTALL} -am -pl :presto-hive
      - name: Run Hive Insert Overwrite Tests
        run: ./mvnw test ${MAVEN_TEST} -pl :presto-hive -P test-hive-insert-overwrite
      - name: Run Hive SSL Enabled Tests
        run: ./mvnw test ${MAVEN_TEST} -pl :presto-hive -P test-ssl-enabled-hms
