name: prestocpp-format-and-header-check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'presto-native-execution/**'
      - '.github/workflows/prestocpp-format-and-header-check.yml'

jobs:
  prestocpp-format-and-header-check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-prestocpp-format-header-check-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - run: python -m pip install pre-commit
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          persist-credentials: false
      - uses: actions/cache@v4.2.3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-
      - name: Run pre-commit
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          files=$(git diff --name-only HEAD^1 HEAD)
          echo "::group::Changed files"
          echo $files | tr ' ' '\n'
          echo "::endgroup::"
          pre-commit run --show-diff-on-failure --color=always --files $files
