name: Presto Stable Release Notes

on:
  workflow_dispatch:

env:
  UPSTREAM: prestodb/presto

jobs:
  release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Check for master branch
        if: ${{ github.ref != 'refs/heads/master' }}
        run: echo "Invalid branch. This action can only be run on the master branch." && exit 1

      - name: Check for personal repository
        if: ${{ github.repository == env.UPSTREAM }}
        run: echo "This action can only be run on personal repository, please clone ${{ env.UPSTREAM }}, and run this action in your own repo" && exit 1

      - name: Checkout presto source
        uses: actions/checkout@v4
        with:
          ref: master
          show-progress: false

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Add git upstream
        run: |
          git remote add upstream https://github.com/${{ env.UPSTREAM }}.git
          git fetch upstream --tags
          git remote -v

      - name: Create release notes pull request
        run: |
          ./src/release/release-notes.sh ${{ github.repository_owner }} ${{ secrets.GITHUB_TOKEN }}