name: prestocpp-format-and-header-check

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - presto-native-execution/**
      - .github/workflows/prestocpp-format-and-header-check.yml

jobs:
  prestocpp-format-and-header-check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-prestocpp-format-header-check-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      - uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
