http-server.http.enabled=false
http-server.https.enabled=true
http-server.https.port=9443
http-server.https.keystore.path=/Users/saitejagoruganthu/presto-func-dev/mTLS_ECDSA_new/function-server/function-server-keystore.jks
http-server.https.keystore.key=changeit
http-server.https.truststore.path=/Users/saitejagoruganthu/presto-func-dev/mTLS_ECDSA_new/function-server/function-server-truststore.jks
http-server.https.truststore.key=changeit
internal-communication.jwt.enabled=true
internal-communication.shared-secret=supersecret
